### PR TITLE
Rename DGmethods to DGMethods

### PR DESCRIPTION
**Pull request by charleskawczynski**
# Description

 - Applies replace-all for "DGmethods" -> "DGMethods"
 - Applies replace-all for "DGmodel" -> "DGModel"

And applies (rename files):
```
git mv src/Numerics/DGmethods/DGmethods.jl          src/Numerics/DGmethods/DGmethodsTMP.jl
git mv src/Numerics/DGmethods/DGmethodsTMP.jl       src/Numerics/DGmethods/DGMethods.jl
git mv src/Numerics/DGmethods/DGmodel.jl            src/Numerics/DGmethods/DGModelTMP.jl
git mv src/Numerics/DGmethods/DGModelTMP.jl         src/Numerics/DGmethods/DGModel.jl
git mv src/Numerics/DGmethods/DGmodel_kernels.jl    src/Numerics/DGmethods/DGModel_kernelsTMP.jl
git mv src/Numerics/DGmethods/DGModel_kernelsTMP.jl src/Numerics/DGmethods/DGModel_kernels.jl
```

And applies (rename folders):
```
git mv test/Numerics/DGmethods/                    test/Numerics/DGmethodsTMP/
git mv test/Numerics/DGmethodsTMP/                 test/Numerics/DGMethods/
git mv tutorials/Numerics/DGmethods/               tutorials/Numerics/DGmethodsTMP/
git mv tutorials/Numerics/DGmethodsTMP/            tutorials/Numerics/DGMethods/
git mv src/Numerics/DGmethods/                     src/Numerics/DGmethodsTMP/
git mv src/Numerics/DGmethodsTMP/                  src/Numerics/DGMethods/
git mv docs/src/HowToGuides/Numerics/DGmethods/    docs/src/HowToGuides/Numerics/DGmethodsTMP/
git mv docs/src/HowToGuides/Numerics/DGmethodsTMP/ docs/src/HowToGuides/Numerics/DGMethods/
git mv docs/src/APIs/Numerics/DGmethods/           docs/src/APIs/Numerics/DGmethodsTMP/
git mv docs/src/APIs/Numerics/DGmethodsTMP/        docs/src/APIs/Numerics/DGMethods/
```

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Closes #389

**Comment by blallen** [comment]
Why the switch?

**Comment by charleskawczynski** [comment]
I think this more accurately follows CamelCase rules for modules

**Comment by charleskawczynski** [comment]
I suppose we could make things even more verbose and change to `DiscontinuousGalerkinMethods`, but I figured we might want to keep it on the shorter side since its so ubiquitous.

**Comment by blallen** [comment]
> I suppose we could make things even more verbose and change to `DiscontinuousGalerkinMethods`, but I figured we might want to keep it on the shorter side since its so ubiquitous.

Haha, I was going to suggest almost the exact same thing and then decided against it for the same reason.

**Comment by kpamnany** [comment]
There's also a `DGmodel.jl` (and `DGmodel_kernels.jl`).

**Comment by charleskawczynski** [comment]
> There's also a `DGmodel.jl` (and `DGmodel_kernels.jl`).

Should this be done in the same PR, you think?

**Comment by kpamnany** [comment]
> Should this be done in the same PR, you think?

🤷‍♂️  Your call.

**Pull request merged**
