### PR TITLE
Added divergence damping and model orientation

### PR DESCRIPTION
**Pull request by ilopezgp**
Added divergence damping and model orientation

# Description

Added 2D divergence damping horizontal flow, model orientation for correct projections and changed the timescale of the problem for more relevant output.

I have

- [X] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [X] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by ilopezgp** [comment]
I see... I think it has to do with code refactoring. Some functions like `vars_state_auxiliary` seem to have been renamed.

**Comment by kpamnany** [comment]
Needs a rebase.

**Comment by ilopezgp** [comment]
@akshaysridhar

**Pull request merged**
