### PR TITLE
disable sysimg script on Windows CI

### PR DESCRIPTION
**Pull request by simonbyrne**
# Description

I have no idea why this is failing, but it is.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by jakebolewski** [comment]
Should we fix this?  It seems like there is an issue with parsing the test set:
https://dev.azure.com/climate-machine/ClimateMachine.jl/_build/results?buildId=4204&view=logs&j=a846d25a-e32c-5640-1b53-e815fab94407&t=777e4b2c-7cad-5027-3b62-2efbb20eb961&l=1283

**Comment by jakebolewski** [comment]
You could just execute the script directly instead of wrapping it in a testset.  It would effectively do the same thing.

**Comment by simonbyrne** [comment]
> Should we fix this? It seems like there is an issue with parsing the test set:

If you can figure out what is going on, then yes.

**Comment by kpamnany** [comment]
[This](https://github.com/JuliaLang/julia/blob/master/stdlib/Test/src/Test.jl#L1072) is the test that's failing.

Maybe just using a bunch of `joinpath()`s in the `include()` will fix it?

**Comment by simonbyrne** [comment]
i don't mind: we just need to figure this out ASAP as CI is currently broken.

**Comment by simonbyrne** [comment]
any objections to merging this now and figuring out what on earth is going on later?

**Comment by jakebolewski** [comment]
Nope.

I think it's just a string escape issue: https://github.com/CliMA/ClimateMachine.jl/pull/1119 if it works we can add it back

**Pull request merged**
