### PR TITLE
Fix `InterpolationConfiguration` for grid stretching

### PR DESCRIPTION
**Pull request by kpamnany**
### Description

Quick fix to use the DG grid's vertical range in `InterpolationConfiguration`.

- [X] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by jiahe23** [comment]
@kpamnany 

I got the following error msg when running `solid_body_rotation_fvm.jl` (on cpu).

```
ERROR: LoadError: MethodError: no method matching ClimateMachine.AtmosGCMSpecificInfo(::Float64, ::Int64, ::Int64, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}})
Closest candidates are:
  ClimateMachine.AtmosGCMSpecificInfo(::FT, ::Int64, ::Int64, !Matched::Array{FT,1}) where FT at /home/jiahe/CliMA/ClimateMachine.jl/src/Driver/driver_configs.jl:19
Stacktrace:
 [1] AtmosGCMConfiguration(::String, ::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}, ::Float64, ::EarthParameterSet, ::typeof(init_solid_body_rotation!); array_type::Type{T} where T, solver_type::IMEXSolverType{HEVISplitting,LowStorageVariant}, model::AtmosModel{Float64,EarthParameterSet,AtmosProblem{Tuple{AtmosBC{Impenetrable{FreeSlip},Insulating,Impermeable,OutflowPrecipitation,ImpermeableTracer,ClimateMachine.TurbulenceConvection.NoTurbConvBC},AtmosBC{Impenetrable{FreeSlip},Insulating,Impermeable,OutflowPrecipitation,ImpermeableTracer,ClimateMachine.TurbulenceConvection.NoTurbConvBC}},typeof(init_solid_body_rotation!),typeof(ClimateMachine.Atmos.atmos_problem_init_state_auxiliary)},SphericalOrientation,EnergyModel,HydrostaticState{DecayingTemperatureProfile{Float64},Float64},ConstantKinematicViscosity{Float64,WithoutDivergence},ClimateMachine.TurbulenceConvection.NoTurbConv,NoHyperDiffusion,NoViscousSponge,DryModel,NoPrecipitation,NoRadiation,Tuple{Gravity{Momentum},Coriolis{Momentum}},NoTracers,NoLSForcing,Nothing}, mpicomm::MPI.Comm, grid_stretching::Tuple{Nothing}, meshwarp::Function, numerical_flux_first_order::RoeNumericalFlux, numerical_flux_second_order::CentralNumericalFluxSecondOrder, numerical_flux_gradient::CentralNumericalFluxGradient, fv_reconstruction::HBFVReconstruction{AtmosModel{Float64,EarthParameterSet,AtmosProblem{Tuple{AtmosBC{Impenetrable{FreeSlip},Insulating,Impermeable,OutflowPrecipitation,ImpermeableTracer,ClimateMachine.TurbulenceConvection.NoTurbConvBC},AtmosBC{Impenetrable{FreeSlip},Insulating,Impermeable,OutflowPrecipitation,ImpermeableTracer,ClimateMachine.TurbulenceConvection.NoTurbConvBC}},typeof(init_solid_body_rotation!),typeof(ClimateMachine.Atmos.atmos_problem_init_state_auxiliary)},SphericalOrientation,EnergyModel,HydrostaticState{DecayingTemperatureProfile{Float64},Float64},ConstantKinematicViscosity{Float64,WithoutDivergence},ClimateMachine.TurbulenceConvection.NoTurbConv,NoHyperDiffusion,NoViscousSponge,DryModel,NoPrecipitation,NoRadiation,Tuple{Gravity{Momentum},Coriolis{Momentum}},NoTracers,NoLSForcing,Nothing},FVLinear{1,ClimateMachine.DGMethods.FVReconstructions.VanLeer}}) at /home/jiahe/CliMA/ClimateMachine.jl/src/Driver/driver_configs.jl:389
 [2] config_solid_body_rotation(::Type{T} where T, ::Tuple{Int64,Int64}, ::FVLinear{1,ClimateMachine.DGMethods.FVReconstructions.VanLeer}, ::Tuple{Int64,Int64}, ::HydrostaticState{DecayingTemperatureProfile{Float64},Float64}) at /home/jiahe/CliMA/ClimateMachine.jl/experiments/TestCase/solid_body_rotation_fvm.jl:79
 [3] main() at /home/jiahe/CliMA/ClimateMachine.jl/experiments/TestCase/solid_body_rotation_fvm.jl:111
 [4] top-level scope at /home/jiahe/CliMA/ClimateMachine.jl/experiments/TestCase/solid_body_rotation_fvm.jl:238
 [5] include(::Function, ::Module, ::String) at ./Base.jl:380
 [6] include(::Module, ::String) at ./Base.jl:368
 [7] exec_options(::Base.JLOptions) at ./client.jl:296
 [8] _start() at ./client.jl:506
in expression starting at /home/jiahe/CliMA/ClimateMachine.jl/experiments/TestCase/solid_body_rotation_fvm.jl:238
```

**Comment by kpamnany** [comment]
Ran `solid_body_rotation_fvm.jl` and uncommented the grid stretching setting. It runs, so you should be able to check the output now.

**Comment by jiahe23** [comment]
Here are test results for solid body rotation and baroclinic wave testcases. They are tested on both DG and FV kernels, with and without stretching.

The diagnostic output match quite well with nodal point values. The discontinuous netcdf profiles for FVM simulations are due to the fact that `lvls` in diagnostic config is set up differently from the FV cell center. This should be left outside this PR and addressed separately.

SBR-fix
BW-fix

**Review by jiahe23 — APPROVED** [review]

**Pull request merged**
