### PR TITLE
WIP: Sketch out of split-explicit for ocean

### PR DESCRIPTION
**Pull request by blallen**
working on multistate multirate runge kutta interface to pass between slow 3D equations and fast 2D equations

### CODE REVIEW

**Comment by jkozdon** [comment]
Couples things:

- I don't think that the `Qslow` will ever be updated, you'll need a call to the `update` from the LSRK solvers after the fast solver
- I think that you may want your reconcile function to involve the rate as well so that you can smear the effect of the slow rate function over all the fast stages (not sure), but otherwise you slow will be locked at the initial stage value
- If you do not do the smearing you don't need all the extra `slow_` arguments to `dostep!` (even with the smearing some more thought might be required to get it all to work) -- alternatively, you could make the reconciled slow state (the integral?) part of the state of the fast solver then get the smearing automatically

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
@jkozdon , I was able to get the LSRK test with a single BL working. Turns out I had a stupid typo and was trying to pull my state out of the source array. 

So for the explicit solvers, I get the expected convergence, for example for the 14 stage LSRK:
```
errors[n] = norm(Q.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.7657662804840941
errors[n] = norm(Q.data[1, :, 1] - exactsolution(ω, finaltime)) = 2.6372138023358676
errors[n] = norm(Q.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.04465310883789714
errors[n] = norm(Q.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.01104308104435997
errors[n] = norm(Q.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.00015251120261145957
errors[n] = norm(Q.data[1, :, 1] - exactsolution(ω, finaltime)) = 2.1420955959479404e-6
errors[n] = norm(Q.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.2266757408921842e-7
rates = log2.(errors[1:end - 1] ./ errors[2:end]) = [-1.7840384975863828, 5.884110104742576, 2.0156178787025145, 6.178083714406011, 6.153748543458194, 4.126197022190247]
```
So close enough to 4th order. But for the MultistateRK the convergence seems to stop at some point
```
error[n] = norm([Qᶠ.data[1, 1, 1], Qˢ.data[1, 1, 1]] - exactsolution(ω, finaltime)) = 4.517414710901052
error[n] = norm([Qᶠ.data[1, 1, 1], Qˢ.data[1, 1, 1]] - exactsolution(ω, finaltime)) = 0.18884839205805373
error[n] = norm([Qᶠ.data[1, 1, 1], Qˢ.data[1, 1, 1]] - exactsolution(ω, finaltime)) = 0.27046331572595406
error[n] = norm([Qᶠ.data[1, 1, 1], Qˢ.data[1, 1, 1]] - exactsolution(ω, finaltime)) = 0.25285455516934896
error[n] = norm([Qᶠ.data[1, 1, 1], Qˢ.data[1, 1, 1]] - exactsolution(ω, finaltime)) = 0.24702926148964013
error[n] = norm([Qᶠ.data[1, 1, 1], Qˢ.data[1, 1, 1]] - exactsolution(ω, finaltime)) = 0.245715646902427
error[n] = norm([Qᶠ.data[1, 1, 1], Qˢ.data[1, 1, 1]] - exactsolution(ω, finaltime)) = 0.24503494478219326
rate = log2.(error[1:end - 1] ./ error[2:end]) = [4.580196957991057, -0.5182044274122004, 0.09712515865508577, 0.033625824557477, 0.0076922144014406986, 0.004002221167431754]
```

Any thoughts about what might be happening?

**Comment by jkozdon** [comment]
> Any thoughts about what might be happening?

I believe that problem is that you have [`dQslow = dQ2fast`](https://github.com/climate-machine/CLIMA/blob/dcbfcf7ac1b487f505da60afaa37335ff91657f2/src/ODESolvers/MultistateRungeKuttaMethod.jl#L111). These always need to be two separate arrays or else the call [`slow.rhs!(dQ2fast, Qslow, param, slow_stage_time, increment = false)`](https://github.com/climate-machine/CLIMA/blob/dcbfcf7ac1b487f505da60afaa37335ff91657f2/src/ODESolvers/MultistateRungeKuttaMethod.jl#L144) will cause problems.

**Comment by blallen** [comment]
> > Any thoughts about what might be happening?
> 
> I believe that problem is that you have [`dQslow = dQ2fast`](https://github.com/climate-machine/CLIMA/blob/dcbfcf7ac1b487f505da60afaa37335ff91657f2/src/ODESolvers/MultistateRungeKuttaMethod.jl#L111). These always need to be two separate arrays or else the call [`slow.rhs!(dQ2fast, Qslow, param, slow_stage_time, increment = false)`](https://github.com/climate-machine/CLIMA/blob/dcbfcf7ac1b487f505da60afaa37335ff91657f2/src/ODESolvers/MultistateRungeKuttaMethod.jl#L144) will cause problems.

Ah yes, I was worried about that. What's a good way for me to get an extra place to store dQ2fast? Will a `similar(dQslow)` statement work to create a container in a safe way?

**Comment by jkozdon** [comment]
> What's a good way for me to get an extra place to store dQ2fast? Will a `similar(dQslow)` statement work to create a container in a safe way?

You probably don't want to put a similar in the tendency evaluation. I'd put it in the [struct definition](https://github.com/climate-machine/CLIMA/blob/dcbfcf7ac1b487f505da60afaa37335ff91657f2/src/ODESolvers/MultistateRungeKuttaMethod.jl#L35-L67) is `sAlt === nothing`

**Comment by blallen** [comment]
Okay, made a change and got the MultistateRK method working for both everything. 

However, the MultistateMultirateRK method, only works for `onestate_in_multistate` with the 5 stage as the slow method and the 14 stage LSRK as the fast method, it really fails for two 14 stage LSRK, and kinda works for the other two combinations. The true `multistate` model fails for all combinations with the MultistateMultirateRK method.

Any ideas on what to test next? I'd like to get the MultistateMultirateRK solver working before making the information passing more complicated.

**Comment by blallen** [comment]
For reference here are the errors and convergence rates for `onestate_in_multistate` test

Slow: 5 stage, Fast: 5 stage
```
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 9.85700519187439
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 10.881801665879463
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 4.2965735687683315
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.016009679403696027
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.0005356281742088
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 2.4860356727889096e-5
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.500572184848777e-6
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 6.967280690280765e-8
rate = log2.(error[1:end - 1] ./ error[2:end]) = [-0.14269614791821536, 1.340658935784098, 8.06809836979726, 4.901568758860396, 4.4293129455991505, 4.050262371761133, 4.428773224853219]
```

Slow: 5 stage, Fast: 14 stage
```
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 5.248009847346643
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 2.812640984644271
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.07558809407136712
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.0015291556005255008
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.4185632340078122e-5
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 3.812407081450577e-7
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.7625660483231655e-7
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.3911977315507416e-8
rate = log2.(error[1:end - 1] ./ error[2:end]) = [0.8998450132746124, 5.217622590996383, 5.627351890591232, 6.752160944845712, 5.217584475872318, 1.1130248552792221, 3.663277929926016]
```

Slow: 14 stage, Fast: 5 stage
```
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 5.829809524725582
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.14536429465967
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 3.7585149252931553
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.029840629036666375
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 6.2731916193313e-5
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.918240394717602e-5
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.5124766815483845e-6
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 7.911751007217702e-8
rate = log2.(error[1:end - 1] ./ error[2:end]) = [2.3476422125269374, -1.7143561978657467, 6.976740974910265, 8.893862600882743, 1.7094161006674147, 3.6647987257827848, 4.256772066353941]
```

Slow: 14 stage, Fast: 14 stage
```
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 1.4385432496361272
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 3.227400791347716
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.050998121708839314
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 0.0037822570170139465
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 2.0470089152538842e-5
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 8.596075752922638e-7
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 8.684464061477305e-9
error[n] = norm(Qᶠ.data[1, :, 1] - exactsolution(ω, finaltime)) = 2.4912190713639685e-9
rate = log2.(error[1:end - 1] ./ error[2:end]) = [-1.1657641523167195, 5.983784825533917, 3.7531248050615393, 7.529586206661078, 4.573695378887595, 6.629097566738819, 1.8015849255795329]
```

I'm confused why changing the slow solver has any effect, since the slow balance law isn't doing anything in this case.

**Comment by jkozdon** [comment]
> I'm confused why changing the slow solver has any effect, since the slow balance law isn't doing anything in this case.

The issue here is that the stage values are different distances for the different slow solvers, so the sub-stepping is different.

If you put all the physics in the slow solver the solutions should be the same.

**Comment by jkozdon** [comment]
> If you put all the physics in the slow solver the solutions should be the same.

see 6d27067

**Comment by blallen** [comment]
Superseded by #1482

**Pull request closed without merging**
