### PR TITLE
Fix rendering of `.mp4` animations in Docs

### PR DESCRIPTION
**Pull request by navidcy**
### Description

This PR fixes the rendering of animations in the Tutorials/Ocean section, e.g., at:
https://clima.github.io/ClimateMachine.jl/latest/generated/Ocean/geostrophic_adjustment/#Running-the-simulation-and-animating-the-results

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by navidcy** [comment]
I don't see any of the tutorials in https://clima.github.io/ClimateMachine.jl/previews/PR2324/ 
weird..

**Comment by charleskawczynski** [comment]
I’m not sure why the tutorials aren’t showing up. Maybe we need to `bors try`? This repo has not really been maintained since we started development on ClimaCore

**Comment by navidcy** [comment]
> I’m not sure why the tutorials aren’t showing up. Maybe we need to `bors try`? This repo has not really been maintained since we started development on ClimaCore

oh, let me close the PR then... no need to bother if the repo is staled

perhaps add a note on the README about repo status?

**Comment by charleskawczynski** [comment]
> perhaps add a note on the README about repo status?

Yes, that's probably a good idea

**Pull request closed without merging**
