### PR TITLE
Revamp advection-diffusion model and add tests on the sphere

### PR DESCRIPTION
**Pull request by mwarusz**
This PR
- Removes standalone hyperdiffusion model
- Adds hyperdiffusion to advection-diffusion model
- Enables choice of components (advection, diffusion, hyperdiffusion) in  advection-diffusion model
- Generalizes advection-diffusion model to solve a system of equations
- Adds convergence test for diffusion and hyperdiffusion PDE on the sphere

### Description

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by mwarusz** [comment]
bors try

**Comment by jkozdon** [comment]
> * Generalizes advection-diffusion model to solve a system of equations

This is awesome. @trontrytel and I had hacked this into the model for the FCT testing, but your way is much cleaner. Love it!

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Review by thomasgibson — APPROVED** [review]
This looks great!

**Pull request merged**
