### PR TITLE
Add soil implicit test haverkamp_implicit_test.jl to pipeline.yml

### PR DESCRIPTION
**Pull request by Zhengyu-Huang**
# Description

Set up an example for using implicit solver for the soil model, this example is in test/Land/Model/haverkamp_test_implicit.jl, add it to CI test.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Review by kmdeck — APPROVED** [review]
hi Daniel, looks good. Line 117-122 in the haverkamp test still look like duplicates but up to you if you remove them or not. 

happy to help you try and squash a branch in the future if you like. Im not sure why there can end up being many conflicts when squashing. I was sort of under the impression that your various commits may conflict with each other, but this may not be it. In any case, squashing can be a little painful sometimes.

**Comment by Zhengyu-Huang** [comment]
> hi Daniel, looks good. Line 117-122 in the haverkamp test still look like duplicates but up to you if you remove them or not.
> 
> happy to help you try and squash a branch in the future if you like. Im not sure why there can end up being many conflicts when squashing. I was sort of under the impression that your various commits may conflict with each other, but this may not be it. In any case, squashing can be a little painful sometimes.

Hi Katherine, thank you! For line 117-122, I think we need it to construct the solver_config, and then we replace the ode solver in it.  Not very familiar with squash, I will definite ask you next time when I prepare PR!

**Comment by kmdeck** [comment]
weird, it failed on CPU but not GPU. https://buildkite.com/clima/climatemachine-ci/builds/368
(can click on red to see error messages). Might be worth asking in the #ci room if this is confusing to you.

**Comment by Zhengyu-Huang** [comment]
bor r+

**Pull request merged**
