### PR TITLE
Shrink dg kernels

### PR DESCRIPTION
**Pull request by charleskawczynski**
# Description

This PR adds a few convenience functions and shortens some names of some things in the DG kernels (mostly to battle the formatter). I'm not 100% sure about these changes, but I wanted to open this PR to hear people's thoughts.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by jkozdon** [comment]
In my opinion a better approach would be to get `Var` / `Grad` out of the kernels completely. Have the kernels deal with straight arrays, and then have the wrapping by `Var` / `Grad` happen in the balance law and / or Numerical flux file.

This would also clean up things like the remainder model where we have to pull out the parent arrays.

So mainly only have `Vars` come into the play when it's needed.

I played around with this idea earlier on one of my branches which you can see here: https://github.com/CliMA/ClimateMachine.jl/commit/a82f049872e16446c8095e2ab43ee46f68bca86e

**Comment by blallen** [comment]
I like this a lot! Seems like a better idea than #1062. 

Maybe to go with @jkozdon's comment, you could make wrapper functions that interface from pure array function calls to the Vars versions?

something like

```julia
function flux_first_order!(
    balance_law, 
    local_flux,
    local_state_prognostic,
    local_state_auxiliary,
    t,
    (direction,),
)
    vs = all_vars_states(balance_law, FT)
    return flux_first_order!(
        balance_law,
        Grad{vs.prognostic}(local_flux),
        Vars{vs.prognostic}(local_state_prognostic),
        Vars{vs.auxiliary}(local_state_auxiliary),
        t, 
        (direction,),
    )
end
```

I think we've mentioned this before but never gotten around to it

**Comment by jkozdon** [comment]
That said, I think we should hold off on this for now.

There is no functionality added with this, but it's going to cause pain for anyone who has PRs working on the kernels.

cc @mwarusz, @thomasgibson

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by jkozdon** [comment]
Personally I liked stuff the old way. This seems more obfuscated to me.

But if others think this is good that’s fine.

**Comment by charleskawczynski** [comment]
> Personally I liked stuff the old way. This seems more obfuscated to me. But if others think this is good that’s fine.

I've updated the PR to remove the `all_number_states`-related changes, but I left the added methods in `dg_element_helper_funcs.jl`, since this will help us document and generalize towards supporting different poly orders in different directions.

**Comment by charleskawczynski** [comment]
We can revive this down the road, but I'll close for now since it's getting stale.

**Pull request closed without merging**
