### PR TITLE
Move around events in `Filters.apply!`

### PR DESCRIPTION
**Pull request by jkozdon**
Fix race conditions due to event dependency  in the `Filter.apply!` when `EveryDirection` is used.

### CODE REVIEW

**Comment by jkozdon** [comment]
@mwarusz and @vchuravy: @sandreza and I were poking around, and found what we think is a possible race condition. @sandreza was seeing some race like conditions with multi-threaded ClimateMachine with the filters and this change seems to have fixed the issue.

Not sure I understand what was wrong before with the dependency, can you offer any insight? (Or is it not really a race conditions and a coincidence.)

**Comment by jkozdon** [comment]
If this is a race conditions, not sure if it would apply to #1953 as well (the events are moved around a bit there)

**Comment by jkozdon** [comment]
@blallen: This might fix #1940

**Comment by blallen** [comment]
> @blallen: This might fix #1940

looks like it did! https://buildkite.com/clima/climatemachine-ci/builds/1243#a3d28eb1-fa28-4062-a8b7-2c9683482c22

just need to lower the precision requirements on something

**Comment by vchuravy** [comment]
Right the `event = Event(Device()` shadows the actual incoming event.

**Comment by mwarusz** [comment]
This looks good to me, but is the pattern
```
event  = if ...
    ...
    event
else
    event
end
```
necessary ?  How is it different from
```
if ...
    event = 
end
```

**Review by mwarusz — APPROVED** [review]

**Comment by jkozdon** [comment]
Thanks @mwarusz

Yeah I originally had a bug in some cases, and didn't think about it when I put in a fix.

**Pull request merged**
