### PR TITLE
Bump OpenMPI and CUDA version

### PR DESCRIPTION
**Pull request by jakebolewski**
Compiled against the ucx version included with the latest mofed with cuda support

### Description

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by jakebolewski** [comment]
bors try

**Review by charleskawczynski — APPROVED** [review]

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
CUDA 11.2 support needs CUDA.jl 3.0+ so closing this in favor of upgrading to Julia 1.6 #2146

**Pull request closed without merging**
