### PR TITLE
Add `--start-datetime` and `ClimateMachine.datetime()`

### PR DESCRIPTION
**Pull request by kpamnany**
### Description

Needed for radiation (when Insolation.jl is added). Defaults to [`J2000`](https://en.wikipedia.org/wiki/Epoch_(astronomy)#Julian_dates_and_J2000).

- [X] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [X] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by skandalaCLIMA** [comment]
looks good to me.

**Comment by skandalaCLIMA** [comment]
bors try

**Comment by kpamnany** [comment]
Strange, looks like BOMEX-LES just took too long?

bors try

**Comment by charleskawczynski** [comment]
> Strange, looks like BOMEX-LES just took too long?

That was strange, last merge it only took ~1hr

**Comment by jakebolewski** [comment]
It might be a hiccup writing out the diagnostics, I think multiple bomex test cases have that enabled

**Comment by jakebolewski** [comment]
@kpamnany maybe we can add a mode where the diagnostics just write to `/dev/null`, that would still sanity check that diagnostics can be written out but reduce the CI variability.

**Review by skandalaCLIMA — APPROVED** [review]

**Pull request merged**
