### PR TITLE
Fix index in reduce_nodal_stack (SingleStackUtils)

### PR DESCRIPTION
**Pull request by jkozdon**
- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
Good catch! Will this require changing the test, also?

**Review by kpamnany — APPROVED** [review]
Good catch!

**Comment by jkozdon** [comment]
> Good catch! Will this require changing the test, also?

Not sure. We'll find out :-)

**Pull request merged**
