### PR TITLE
Clean up AtmosModel constructor

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This PR
 - Unifies the GCM / SingleStack / LES constructors, since the only difference is the orientation
 - Removes the type parameters from the constructors, since there are no restrictions on the types anyway.
 - Changes `turbulence::T = SmagorinskyLilly{FT}(0.21),` to `turbulence = SmagorinskyLilly{FT}(C_smag(param_set))` for `::Union{Type{AtmosLESConfigType}, Type{SingleStackConfigType}}` constructors, since [this is the default in CLIMAParameters.jl](https://github.com/CliMA/CLIMAParameters.jl/blob/master/src/Atmos/atmos_parameters.jl#L4) anyway.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Review by ilopezgp — APPROVED** [review]

**Pull request merged**
