### PR TITLE
updated eq test

### PR DESCRIPTION
**Pull request by kmdeck**
added Richards tutorial

# Description

This adds a tutorial for solving Richards equation, uncoupled with heat.

I have

- [X] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [X] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by kmdeck** [comment]
one these docs build, will proof read and add to the summary of tutorials, PR 1575

**Comment by simonbyrne** [comment]
@kmdeck did you still want to get this in the release?

**Comment by kmdeck** [comment]
> @kmdeck did you still want to get this in the release?

Hi @simonbyrne, my apologies, I was on a backpacking trip M and Tuesday. It's OK for this not to be in the release! I'll move it back to draft status.

**Comment by simonbyrne** [comment]
No problem!

**Comment by kmdeck** [comment]
this tutorial is added as part of https://github.com/CliMA/ClimateMachine.jl/pull/1675

**Pull request closed without merging**
