### PR TITLE
Unify problem interface between SWModel and HBModel

### PR DESCRIPTION
**Pull request by blallen**
# Description

Share Problem structure between various Ocean models to reduce code duplication. 

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [x] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
Bors try

**Comment by blallen** [comment]
bors try

**Comment by vchuravy** [comment]
bors  p=1

**Pull request merged**
