### PR TITLE
All changes from branch "jmc/split_explicit_draft" (from PR #1486)

### PR DESCRIPTION
**Pull request by jm-c**
Make a clean PR from PR #1486 (branch: jmc/split_explicit_draft),
which contains the following list of commits:

- First version of ocean Split-Explicit time-stepping
    Bring up-to-date in latest code the first version of Split-Explicit time-stepping
    for hydrostatic oceanic set of equations that was developed in branch
     "jmc/split_explicit_dvlp" (created in Mar 30, 2020).
    This code provides the same functions and give the same results as code on
     branch: jmc/split_explicit_dvlp - tag: "split-explicit_003" (Jun 01)
    - Use specific time-stepping (SplitExplicitLSRK2nMethod.jl) in ODESolvers
      and specific model from: Ocean/SplitExplicit01
    - Minimal set of changes from old code (but many names changed);
    - For now, add simple function "basic_grid_info" (used to be in DGmodel.jl)
      to Ocean/SplitExplicit01/SplitExplicitModel.jl ; will not be needed anymore
      once PR #1071 is merged.
- Add simple set-up to run Split-Explicit ocean-box
    Taken from old branch: jmc/split_explicit_dvlp (tag: split-explicit_003)
    and updated to run with updated split-explicit code:
    Run a simple box problem (similar to "ocean_gyre) for 15.d with a time step of 90.mn
- shorter run and add StateCheck reference value
- Merge branch 'master' into jmc/split_explicit_draft
- Apply corresponding updates after merging the latest:
    - ClimateMachine.cli has been replaced by: ClimateMachine.init(parse_clargs = true)
    - function "basic_grid_info" is now part of DGModel.jl
    - add specific code to replace call to fct "copy_stack_field_down!" (which has been
      removed).
- Upgrade reshaping in tendency_from_slow_to_fast!
    Use similar transformations as for replacement of copy_stack_field_down!
    to do: apply same rules for reconcile_from_fast_to_slow!
- Reduce precision threshold for Eta
    Reduce precision threshold from 12 to 8:
     since the domain average of Eta is supposed to be zero, the mean value
     is much smaller than the field range and is more likely to change due
     to machine truncation.
- Upgrade reshaping in reconcile_from_fast_to_slow!
    Use similar transformations as for replacement of copy_stack_field_down!
    so that it should work also on GPU.
- Also upgrade reshaping in update_auxiliary_state!
    Use similar transformations as for replacement of copy_stack_field_down!
    so that it should work also on GPU.
- Fix previous changes to work on GPU
    Also improve some variable names from previous changes
- Prep for enabling implicit vertical diff
    o adds IVDC model
    o adds initialization hooks for model and solver
    o does not have code to use IVDC model yet
- Add CUDA to use CuArray in any setting
- Running solver on GPU
- Stepping forward (CPU and GPU)
- Minor changes for IVDC settings:
    New parameters that allow to easily be changed:
     - number of Implicit sub-time step:
       was hard coded before and is now a model parameter: numImplSteps
     - set time-step for IVDC model according to main model time-step (slow_dt) and numImplSteps;
       to do this, I just removed ivdc_dt from IVDCModel params (was hard coded anyway)
       and move it to main model set-up parameter.
     - new convective vertical diffusivity parameter (same as in new master branch), was hard coded
       before. Also went back to usual criteria: dTdz < 0 instead of dTdz < 1.e-10 so that
       it will not over mix neutrally stable water.
     - use model (background) vertical diffusivity, half in the IVDC solver (hard coded before)
       and half in the explicit RK OceanModel.
- Update Split-Explicit testing scripts
    - Update "simple_box_2dt.jl", still without convective adjustment (and no IVDC)
    - New test script "simple_box_ivd.jl" with  convective adjustment and IVDC,
      with reference StateCheck values for a 5.d run.
- Move SplitExplicit01 inside Ocean module
- move down Ocean.jl include in ClimateMachine.jl
- move file: SplitExplicitLSRK2nMethod.jl
    Since this is very specific to one type of oceanic split-explicit, move this
    time-stepper to dir: Ocean/SplitExplicit01 (with other ocean split-explicit files).
- Fix various paths after the move.
- write *.pvtu file when using more than 1 MPI proc
    Adapted from @christophernhill branch, so that paraview can easily load full
    set of files (covering full domain).
- Move gravity inside "pkin" to make it the kinematic pressure
    Also use new variable name "buoy" (for buoyancy) as integrands, that can
    easily account for salinity in EOS.
    Update output reference value (since pkin has changed).
- Update with recent code changes.
    - make changes in this branch code to accommodate with recent code changes in master
      (from June 30, after PR 1301 got merged in, to Aug 21, after PR #1454 got merged in).
    - still to fix: calculation of vertical velocity
    Note: Can reproduce same results as before when running without temperature advection
     (in this case, vertical velocity is not used).
- Fix vertical velocity calculation
    Also bring back an old bug (double call to filters) to get back older results.
- Fix double call to filters in SplitExplicit01/OceanModel.jl
    This affects results ; update reference State-Check values in
     simple_box_2dt_refvals.jl & simple_box_ivd_refvals.j
- Simplify:
    Functions initialize_fast_state! and initialize_adjustment!
    are only used locally inside SplitExplicit01 module so no need
    to have then listed within BalanceLaws.
- Update argument list of fct "init_state_auxiliary!"
- apply formatter
- Try to fix docs built
- Fix call to "writepvtu"
    Adjust call to function "writepvtu" to reflect the changes made in PR #1337
    (merged in on Jul 09) to fix pvtu file when outputting Float32 data.
- add simple box ivd test (slurm test)
- Patches for testing
    - fix ntasks
    - switch off VTK to avoid strange mkdir error for now

# Description

First working version of ocean model, using first version of split-explicit time-stepping and implicit vertical diffusion.
Currently, this is the only ocean code we have that allows long simulations (without statically unstable columns
preventing the integration to continue).

All pieces of code are kept in separate dir: src/Ocean/SplitExplicit01 with minimal changes to the remaining part of the code ;
2 set-up run are provided (in test/Ocean/SplitExplicit: simple_box_2dt.jl & simple_box_ivd.jl) with reference output values
to check against.
Implicit vertical diffusion code is from @christophernhill , merged in into this branch.
it bring back the original way (back from September 2019, branch jek/ocean3d) of dealing with continuity equation
 (used to compute vertical velocity). This feature is intended to stay until the ocean model is able to deal with realistic
coastlines and sloping bottom on the sphere, with non-linear free-surface and perfect (and checked) tracer conservation.
At that point, can be re-evaluated.

Comment:
provide an example of how to generate new reference values for StateCheck, using call to StateCheck.scprintref
although this functionallity is current unusable (as a result of PR #1331).

co-authors: @christophernhill and @blallen 

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [x] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by blallen** [comment]
bors try

**Comment by jm-c** [comment]
bors

**Comment by jm-c** [comment]
bors try

**Review by blallen — APPROVED** [review]
Passes let's go

**Pull request merged**
