### PR TITLE
Update compat to 1.5

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

Update Compat, and some docs, to julia 1.5.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by jakebolewski — APPROVED** [review]

**Review by simonbyrne — APPROVED** [review]

**Comment by kpamnany** [comment]
As this is likely to timeout anyway, letting 1958 through.

bors r-

**Pull request merged**
