### PR TITLE
Reverse sign of gradient flux states in HB Model

### PR DESCRIPTION
**Pull request by blallen**
# Description

Makes things make more physical sense and imposing boundary conditions easier.

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [x] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [x] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
> Seems fine to me. You are just pushing the minus sign somewhere else.

Just wanted some extra eyes on this. I'm splitting out components of #851 into separate PRs because that one is failing the tests, but I don't know which change is causing it.

**Comment by blallen** [comment]
bors try

**Comment by jm-c** [comment]
@blallen Do you get the same StateCheck numbers (using Chris basic stats tools, PR #1118, which I found very useful)  before and after this sign change, e.g. with experiments/Ocean_BoxGCM/ocean_gyre.jl ?

**Comment by blallen** [comment]
> @blallen Do you get the same StateCheck numbers (using Chris basic stats tools, PR #1118, which I found very useful) before and after this sign change, e.g. with experiments/Ocean_BoxGCM/ocean_gyre.jl ?

I haven't because it's not in master :( @christophernhill are you able to help me set this up?

**Comment by christophernhill** [comment]
> > @blallen Do you get the same StateCheck numbers (using Chris basic stats tools, PR #1118, which I found very useful) before and after this sign change, e.g. with experiments/Ocean_BoxGCM/ocean_gyre.jl ?
> 
> I haven't because it's not in master :( @christophernhill are you able to help me set this up?

Brandon - yes. The code is in cnh/statestats02 branch ( https://github.com/CliMA/ClimateMachine.jl/tree/cnh/statestats02 ). You should just need the one StateStats.jl file that is in Diagnostics/Debug. Once you have that you can add 

```
    ## Create a callback to report state statistics for main MPIStateArrays
    ## every ntFreq timesteps.
    ntFreq=30
    cb=ClimateMachine.StateCheck.sccreate( [ (solver_config.Q,"Q",),
                                              (solver_config.dg.state_auxiliary,"s_aux",),
                                              (solver_config.dg.state_gradient_flux,"s_gflux",) ],
                                            ntFreq; prec=12 )

```

just before invoke the ODE solver, 
and add an extra callback

```
    result = ClimateMachine.invoke!(solver_config; user_callbacks=[cb] )
```

That should be enough to get some numbers you can check manually.  

I am not sure where things are with PR review to get it onto master. @skandalaCLIMA was going to take a look, but not sure if he has had time yet.

**Comment by blallen** [comment]
Comparing https://github.com/christophernhill/temp-clima-statetools/blob/master/test/Ocean/HydrostaticBoussinesq/test_ocean_gyre_refvals.jl#L43-L61 against

```
# SC +++++++++++ClimateMachine StateCheck call-back start+++++++++++++++++
# SC  Step  |   Label    |  Field   |                            Stats                       
# SC =======|============|==========|              min() |              max() |             mean() |              std() |
# SC 0000060| ocean state|     u[1] | -3.597786794639e-02|  5.019287789545e-02|  2.838034682947e-03|  1.050607042258e-02|
# SC 0000060| ocean state|     u[2] | -9.264524542827e-02|  1.398725467288e-01| -1.626986024078e-03|  1.573574914830e-02|
# SC 0000060| ocean state|        η | -6.301657024336e-01|  6.334046687920e-01| -1.312828981867e-03|  2.257722497521e-01|
# SC 0000060| ocean state|        θ |  1.830524417999e-04|  9.077859681360e+00|  2.499489310043e+00|  2.197259310479e+00|
# SC 0000060|   ocean aux|        w | -4.665506923877e-05|  5.323540275057e-05|  5.980279173441e-07|  9.202782834364e-06|
# SC 0000060|   ocean aux|     pkin | -9.005334296243e-01|  0.000000000000e+00| -3.320712652855e-01|  2.562286272998e-01|
# SC 0000060|   ocean aux|      wz0 | -2.225585772660e-05|  1.563694461717e-05| -4.002444010165e-08|  7.764972834622e-06|
# SC 0000060|   ocean aux|        y |  0.000000000000e+00|  4.000000000000e+06|  2.000000000000e+06|  1.180252702815e+06|
# SC 0000060|  ocean grad|   ν∇u[1] | -2.107253944720e-03|  2.068245445645e-03|  9.691017886194e-09|  1.537476925590e-04|
# SC 0000060|  ocean grad|   ν∇u[2] | -2.170864923621e-03|  1.943144626776e-03|  7.772036487416e-06|  3.092145711223e-04|
# SC 0000060|  ocean grad|   ν∇u[3] | -1.364895650588e-05|  6.724383381147e-06|  8.192110645625e-09|  1.000666369732e-06|
# SC 0000060|  ocean grad|   ν∇u[4] | -6.578693537840e-03|  6.979225861389e-03| -8.431426704435e-06|  3.612672093589e-04|
# SC 0000060|  ocean grad|   ν∇u[5] | -7.175125487912e-03|  1.366162606393e-03| -1.137858705820e-05|  3.915192544269e-04|
# SC 0000060|  ocean grad|   ν∇u[6] | -1.394198591133e-05|  1.285529135310e-05| -3.298795173924e-08|  1.950400793353e-06|
# SC 0000060|  ocean grad|    κ∇θ[1 | -6.559548621086e-05|  7.804719618274e-05| -2.685695929155e-06|  8.510408923112e-06|
# SC 0000060|  ocean grad|    κ∇θ[2 | -7.116064863979e-05|  3.093815378379e-03|  9.819529012452e-04|  8.313194026287e-04|
# SC 0000060|  ocean grad|    κ∇θ[3 | -4.214770190371e-05|  4.008480282925e-05| -5.350740415469e-07|  3.493023767913e-06|
# SC +++++++++++ClimateMachine StateCheck call-back end+++++++++++++++++++
```

it looks like everything is the same besides changing the signs on the gradient fluxes, so this PR is doing exactly what we want it to.

**Comment by blallen** [comment]
Got verbal approval from @jm-c today, gonna merge this now

**Pull request merged**
