### PR TITLE
Move direction to BalanceLaw

### PR DESCRIPTION
**Pull request by simonbyrne**
This should make it easier to compose models.

### CODE REVIEW

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try-

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
@lcw I'm not sure exactly what you mean can you expand on it?

I do know there are still lots of issues we need to figure out (i.e. how we handle multirate stuff, especially 2nd derivatives), but this seemed like a reasonable way forward.

**Comment by lcw** [comment]
I was just thinking about what would happen if you tried to use the remainder model with balance laws with different directions.  Right now I don't think that would work.

**Comment by simonbyrne** [comment]
Yeah, that will require separate kernel calls, which is not ideal.

We can do the necessary projections in the balance laws themselves, but if we're going to do that, it might be worth thinking about a local rotated coordinate system.

**Comment by charleskawczynski** [comment]
Can `direction` be given a more descriptive name?

**Comment by bischtob** [comment]
@simonbyrne, is this PR still relevant?

**Pull request closed without merging**
