### PR TITLE
Brings entropy stable and split form kernels up to date with master [WIP]

### PR DESCRIPTION
**Pull request by sandreza**
### Description

Entropy stable and split form kernels are being brought up to date with master. This is all thanks to the hard work by @jkozdon @lcw @mwarusz and @thomasgibson 

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by blallen** [comment]
bors try

**Comment by sandreza** [comment]
bors try

**Comment by blallen** [comment]
bors try

**Comment by sandreza** [comment]
bors try

**Review by charleskawczynski — APPROVED** [review]
I've discussed the features added in this PR with @sandreza / @mwarusz / @bischtob, and it seems that this PR adds a regression test with a working (stable) moist baroclinic wave without filters.

This PR does add a _lot_ of code duplication, but the added regression test will allow us to safely and easily remove the duplication once it's merged. Ideally we'd boil this PR down to the core added functionality with the regression test, however, that has some risks:
 - Master could become incompatible with the PR
 - The branch could become broken / unfixable if we're not very careful
 - People who'd like to test and use this feature will need to wait until it's ready, which may take a long time

IMO, I'm fine with merging as is, and opening a bunch of issues on several points.

cc: @simonbyrne, @kpamnany thoughts?

**Comment by sandreza** [comment]
bors try

**Review by blallen — APPROVED** [review]
let's merge it!

**Pull request merged**
