### PR TITLE
modify the isothermal zonal flow test case and move it to TestCase folder

### PR DESCRIPTION
**Pull request by jiahe23**
### Description

This PR updates the isothermal zonal flow in:
1. replacing the default Rusanov flux by Roe flux;
2. adding a test assert to ensure the flow stay identical to its initial state;
3. moving the test driver into `TestCase`

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by szy21** [comment]
It seems the initial state of this test is not in discrete hydrostatic balance? I'm not sure though.

**Comment by jiahe23** [comment]
> It seems the initial state of this test is not in discrete hydrostatic balance? I'm not sure though.

Good catch! I need to double check the calc for pressure and density.

**Review by kpamnany — APPROVED** [review]
LGTM but can't comment on the balance.

**Comment by jiahe23** [comment]
> It seems the initial state of this test is not in discrete hydrostatic balance? I'm not sure though.

I've consulted Maciej and Thomas. The initial condition is balanced analytically but not discretely. For now, this is the best we could do [we cannot simply copy the way the ref state is set up because there's flow]. 

The fact that the state var stays identical indicates that the discrepancies are small enough to be ignored.

**Pull request merged**
