### PR TITLE
Jmc/split explicit draft

### PR DESCRIPTION
**Pull request by jm-c**
# Description

First working version of ocean model, using first version of split-explicit time-stepping and implicit vertical diffusion.
Currently, this is the only ocean code we have that allows long simulations (without statically unstable columns
preventing the integration to continue). 
1) Not in final form or ready to merge yet ; kept linear git history (no rebase for now) to help track of what got changed.
2) all pieces of code are kept in separate dir: src/Ocean/SplitExplicit01 with minimal changes to the remaining part of the code ; 
  2 set-up run are provided (in test/Ocean/SplitExplicit: simple_box_2dt.jl & simple_box_ivd.jl) with reference output values
  to check against.
3) Implicit vertical diffusion code is from @christophernhill , merged in into this branch.
4) it bring back the original way (back from September 2019, branch jek/ocean3d) of dealing with continuity equation
  (used to compute vertical velocity). This feature is intended to stay until the ocean model is able to deal with realistic
  coastlines and sloping bottom on the sphere, with non-linear free-surface and perfect (and checked) tracer conservation.
  At that point, can be re-evaluated.

Comment:
   provide an example of how to generate new reference values for StateCheck, using call to StateCheck.scprintref
   although this functionallity is current unusable (as a result of PR #1331).

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by blallen** [comment]
bors try

**Comment by blallen** [comment]
@jm-c is there anything else you want to add to this branch before we merge it?

**Comment by jm-c** [comment]
There would be few things to change, but it can be done later (and probably better anyway). 
My main question is: would you need to rebase ? or is it enough to squash-merge it into master ?

**Comment by blallen** [comment]
> There would be few things to change, but it can be done later (and probably better anyway). My main question is: would you need to rebase ? or is it enough to squash-merge it into master ?

It's enough to just squash-merge into master. Probably the only thing we want to do is add the `simplebox_ivdc.jl` file to the slurm tests so that we make sure it doesn't break

**Comment by christophernhill** [comment]
@jm-c and @blallen this looks great. Hopefully Bors agrees!

**Comment by blallen** [comment]
bors try

**Comment by christophernhill** [comment]
bors try

**Comment by christophernhill** [comment]
bors try

**Comment by blallen** [comment]
@jm-c can you squash this so we can merge? andre has reported that there are improvements to the BGMRES solver that aren't present here and that will help with time to solution

**Comment by jm-c** [comment]
Put all the changes from this branch into new PR #1550 (branch: jmc/split_explicit_draft2merge) so should close this PR once
#1550 is merged in.

**Comment by jm-c** [comment]
bors try

**Comment by jm-c** [comment]
PR #1550 got merged in so no need to keep this one.

**Pull request closed without merging**
