### PR TITLE
change poly order in baroclinic_wave.jl for QA purposes

### PR DESCRIPTION
**Pull request by szy21**
### Description

This PR changes the polynomial order in experiments/TestCase/baroclinic_wave.jl to (5, 6) for QA purposes.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by szy21** [comment]
It failed on day 18 (due to some instability?), but it is only run for 15 days in QA, so it should be fine.

**Review by kpamnany — APPROVED** [review]
Looks fine to me. Assume you've run it with diagnostics enabled?

**Comment by szy21** [comment]
> Looks fine to me. Assume you've run it with diagnostics enabled?

Yes. The diagnostics looks ok.

**Pull request merged**
