### PR TITLE
Clean up thermo tests

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This PR adds a few helpers to clean up some of the thermo tests.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Review by glwagner — APPROVED** [review]
Good formatter-foo.

**Comment by charleskawczynski** [comment]
👊🏻

**Pull request merged**
