### PR TITLE
Better docstring for --cutoff-degree CL option

### LINKED ISSUE #2047: Filter `Nc` versus driver `Ncutoff`
Currently the driver `Ncutoff` means "[Keep all polynomial modes below `Ncutoff`](https://github.com/CliMA/ClimateMachine.jl/blob/711360d0386d2edbb0dc78d110c0c9a654f9e818/src/Driver/driver_configs.jl#L406-L414)" whereas the filter `Nc` means "[filter all modes `Nc` and higher".](https://github.com/CliMA/ClimateMachine.jl/blob/711360d0386d2edbb0dc78d110c0c9a654f9e818/src/Numerics/Mesh/Filters.jl#L101-L112)

I understand why this was done in #1953.

I fear this will lead to some confusion, so I wonder if we should change the meaning of `Nc` in the filter code or determine a better way to specify no filter in the driver.

cc: @valeriabarra @simonbyrne

### PR DESCRIPTION
**Pull request by valeriabarra**
### Description
Will this close #2047  ? 
cc: @jkozdon , @simonbyrne 

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Review by jkozdon — APPROVED** [review]
Looks fine to me. Thanks.

**Comment by valeriabarra** [comment]
@jakebolewski I am not sure how to fix the bors failure in this PR. 
This PR only changed one docstring and the formatter runs clean for me locally. Any clue? Thanks

**Comment by jakebolewski** [comment]
Looks like a spurious failure with a GA step, I would just try again.

**Comment by jakebolewski** [comment]
Looks like something on the Github Action runner side changed, so we'll have to wait for the bugfix to propagate: https://github.com/dorny/paths-filter/releases/tag/v2.9.1

**Comment by valeriabarra** [comment]
Thanks @jakebolewski . 
How should we proceed? Apply a workaround? 
Is it something like you did in #2096 needed?

**Comment by jakebolewski** [comment]
rebase on `master` should fix the issue

**Pull request merged**
