### PR TITLE
Apply abs to temperature in sat adjust

### PR DESCRIPTION
**Pull request by charleskawczynski**
# Description

At the moment, `saturation_adjustment` failures can occur because `find_zero` cannot find the root, or because `find_zero` searches for `T` for `T<0`, which results in `DomainError` (`saturation_vapor_pressure(T) ~ (T / _T_triple)^(Δcp / _R_v)`). Rather than implementing bracketing tooling in RootSolvers.jl, this PR effectively brackets temperature by applying `abs` to temperature in `find_zero` (and wraps the result in `abs`). The upside of this PR is that, IIUC, ThermodynamicState input parameters will now always be reported when convergence fails. Before this PR, ThermodynamicState input parameters are reported so long `DomainError` does not occur. This should help us more gracefully handle, and collect data for, non-converged saturation adjustment cases.

This is one more small step towards fixing #263. This also opens some doors with #1510, in particular, we could store `converged::Bool` in the `PhaseEquil` state, and query whether any states are not converged, rather than doing `try-catch`.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by tapios** [comment]
Reflecting temperatures about zero with `abs` seems risky to be. It would be better to truncate: replace `T` by `T * H(T)` with Heaviside function `H`.

**Comment by charleskawczynski** [comment]
> Reflecting temperatures about zero with `abs` seems risky to me. It would be better to truncate: replace `T` by `T * H(T)` with Heaviside function `H`.

I'm not sure I see any risk since `T` is the only variable in the root finding algorithm. What's the concern? a Heaviside function will zero out gradients and be problematic for gradient-based search algorithms.

**Comment by tapios** [comment]
> > Reflecting temperatures about zero with `abs` seems risky to me. It would be better to truncate: replace `T` by `T * H(T)` with Heaviside function `H`.
> 
> I'm not sure I see any risk since `T` is the only variable in the root finding algorithm. What's the concern? a Heaviside function will zero out gradients and be problematic for gradient-based search algorithms.

`abs` has a discontinuous derivative at 0 too. The problem is that projecting `T<0` to `T>0` is just completely physically wrong. Projecting `T<0` to `0` is more acceptable (and is how we deal with these situations, e.g., in positivity preserving ODE solvers). The gradients are analytical for the Newton method anyway, so truncating does not present a special problem as far as I can see.

**Comment by charleskawczynski** [comment]
I see. Thinking out loud, on second thought this should be fine because we'll likely not converge regardless of `abs`/`heaviside` so, even if the gradients are zero, we're really only trying to avoid `DomainError`. I'll go update.

**Comment by charleskawczynski** [comment]
Updated.

**Comment by charleskawczynski** [comment]
@tapios should we merge this? And if so, can you approve?

**Review by tapios — APPROVED** [review]

**Pull request merged**
