### PR TITLE
Move solver_type to SolverConfiguration

### LINKED ISSUE #1985: Make constructing implicit solvers simpler
### Description

In certain situations (e.g., [here](https://github.com/CliMA/ClimateMachine.jl/blob/master/test/Atmos/EDMF/stable_bl_single_stack_implicit.jl#L72-L147)), constructing implicit solvers involves constructing a driver, constructing a solver configuration, and [going back and re-defining pieces of the solver configuration](https://github.com/CliMA/ClimateMachine.jl/blob/master/test/Atmos/EDMF/stable_bl_single_stack_implicit.jl#L147). This is awkward and, IIRC, the simple solution to fix this problem is to move the solver type from the driver to the solver configuration (and then revamp some constructors). It is a bit odd to have `solver_type` defined in `driver_config` instead of `solver_config`.

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This PR moves `solver_type` from `DriverConfiguration` to `SolverConfiguration`.

There are two reasons why this seems to be a good idea. 

 - `solver_type` seems like it belongs in `SolverConfiguration` to begin with 
 - `solver_type` is not used in any of the `DriverConfiguration` constructors, however, it _is_ used in the `SolverConfiguration` constructor
 - It can make certain solver configurations difficult to construct (see #1985)

Closes #1985.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Review by jakebolewski — APPROVED** [review]
LGTM

**Pull request merged**
