### PR TITLE
add simple rain CI checks

### PR DESCRIPTION
**Pull request by trontrytel**
### Description

This PR adds a simple CI test for rain and moisture variables for LES dycoms case.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
Looks good. Should we put this in a separate function/file `sanity_test(m::AtmosModel, Q)`, as I could imagine these tests/checks getting large and maybe bloating the driver?. Also, we can check `m isa NonEquilibrium` in `sanity_test` instead of `moisture_model == "nonequilibrium"` so that we don't need to pass tons of arguments through (same with the precip model).

**Review by jakebolewski — APPROVED** [review]
:100:

**Comment by trontrytel** [comment]
> Looks good. Should we put this in a separate function/file `sanity_test(m::AtmosModel, Q)`, as I could imagine these tests/checks getting large and maybe bloating the driver?. Also, we can check `m isa NonEquilibrium` in `sanity_test` instead of `moisture_model == "nonequilibrium"` so that we don't need to pass tons of arguments through (same with the precip model).

I'm piggybacking on an existing LES experiment for Dycoms. The default setup there is `noprecip` and `equilibrium` options. Thats why I added the command line arguments for it. 

Not sure what is the right folder structure. Up to you guys, I have no preference either way

**Pull request merged**
