### PR TITLE
Add / extract vars wrappers in DG kernels / BalanceLaws

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This is a continuation of #1947. Basically, these PRs are thinning the layer in which `Vars` is used.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
It looks like the numerical fluxes are the only ones left, so I'll try to tackle that next.

**Review by jkozdon — APPROVED** [review]
LGTM!

**Comment by jkozdon** [comment]
> It looks like the numerical fluxes are the only ones left, so I'll try to tackle that next.

🚀

**Pull request merged**
