### PR TITLE
Fix broken `Writers` test

### PR DESCRIPTION
**Pull request by kpamnany**
# Description

Unsure how this passed CI. We're investigating.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [X] There are no open pull requests for this already
- [X] CLIMA developers with relevant expertise have been assigned to review this submission
- [X] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [X] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by jakebolewski** [comment]
Hmm looks like some Anaconda package issues again, will retry.

**Comment by simonbyrne** [comment]
hopefully those should be resolved soon: https://github.com/Alexander-Barth/NCDatasets.jl/pull/88

**Pull request merged**
