### PR TITLE
Fix identity operation in reduce_nodal_stack

### PR DESCRIPTION
**Pull request by jkozdon**
- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
I see what you mean, @jkozdon, about the double counting on the first nodal stack. This looks like a bug fix.

**Review by kpamnany — APPROVED** [review]
Good catch!

**Comment by jkozdon** [comment]
Looking at this test more, it seems to me that using `+` or `*` in the `reduce_nodal_stack` is really weird. I'll leave them for now, but it's just a bit odd (since the returned `z` value doesn't really mean anything in this case)

**Comment by jkozdon** [comment]
> Looking at this test more, it seems to me that using `+` or `*` in the `reduce_nodal_stack` is really weird. I'll leave them for now, but it's just a bit odd (since the returned `z` value doesn't really mean anything in this case)

To clarify, I think the code still does the right thing for the result, it's just the `z` value doesn't have a well defined meaning.

**Pull request merged**
