### PR TITLE
Abstract array device discovery

### PR DESCRIPTION
**Pull request by kpamnany**
# Description

Expand and export `MPIStateArray`s `device()` as `array_device()`. This simplifies adding types such as `SubArray`, as produced by `view()`, which we're using in diagnostics.

Replace all occurrences of:
```
device = typeof(x) <: Array ? CPU() : CUDA()
```
and similar with:
```
device = array_device(x)
```

And:
```
host_array = Array ∈ typeof(Q).parameters
```
and similar with:
```
array_device(Q) isa CPU
```
Exceptions are where `using MPIStateArrays` would violate modularity:
- `src/Arrays/CMBuffers.jl` -- defines its own `device()`
- `src/Numerics/Mesh/Filters.jl` -- tests `Q.data`
- `src/Numerics/Mesh/Grids.jl` -- tests `grid.vgeo`

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [X] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [X] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by kpamnany** [comment]
> Though, why not just `device`?

As was commented in `MPIStateArrays.jl`, `device` is also defined in `CUDAdrv`.

**Comment by jkozdon** [comment]
> As was commented in `MPIStateArrays.jl`, `device` is also defined in `CUDAdrv`.

Very good. Didn't read the deleted comment. Thanks.

**Comment by charleskawczynski** [comment]
Looks great. Might it make sense to merge this after #1150?

**Pull request merged**
