### PR TITLE
Move long tests to buildkite

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This PR moves some of the longer tests over to buildkite, to help with CI. To note, some tests are already being run in buildkite, so they were just removed from the GHA CI.

Maybe we can revert this once #1952 is fixed.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
It looks like this will bring our CI times back down to < 1hr.

**Comment by simonbyrne** [comment]
Thanks @charleskawczynski. Fine by me, any thoughts @jakebolewski ?

**Review by kpamnany — COMMENTED** [review]
GHA gives us cross-platform testing. Not sure if the tests moved will weaken our assurance of platform portability; I would guess not, but if we're not sure, perhaps it would be better to keep a representative test from each group on GHA rather than move entire groups?

**Comment by jakebolewski** [comment]
This LGTM, I agree that we loose x-platform testing but I don't know if longer term that will honestly be sustainable for expensive tests as the number of tests just continues to increase.

**Review by jakebolewski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Had to fix a few labels (they were not unique on the first few r+'s)

**Comment by charleskawczynski** [comment]
Ok, maybe not quite < 1 hr, but we're close

**Pull request merged**
