### PR TITLE
Use many threads for stack in set banded matrix

### PR DESCRIPTION
**Pull request by jkozdon**
@Zhengyu-Huang I was originally thinking that we should use multiple threads per stack element (as opposed to one thread per stack element)

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
Hmm... maybe we cannot bors a non-master PR

**Review by simonbyrne — APPROVED** [review]

**Comment by jkozdon** [comment]
This wasn't meant to be merged.

**Comment by thomasgibson** [comment]
@jkozdon We should talk about these changes. I was under the impression there were still issues?

**Comment by jkozdon** [comment]
> @jkozdon We should talk about these changes. I was under the impression there were still issues?

The real PR is #1512. I need to fix some of the testing and look into the Float32 issue some more.

**Pull request closed without merging**
