### PR TITLE
Diagnostics group for perturbations from horizontal averages

### LINKED ISSUE #1243: Additional perturbation quantities in NETCDF output
# Description

Currently profiles of variances are horizontally averaged, then stored. An optional utility that would be helpful is a field of the perturbations and variances about the horizontal averages.

`q'(x,y,z,t) = q(x,y,z,t) - <q>(z,t)`

cc @kpamnany 

# Additional context

Adds another diagnostic utility that should facilitate greater flexibility in experiment design and analysis. In the longer term, it is perhaps worth thinking about decoupling the mathematical kernels from the diagnostics write-out step, since some of these quantities may be required in the model equations. 

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

### PR DESCRIPTION
**Pull request by kpamnany**
# Description

For LES configurations. Requires that an `InterpolationConfiguration` be provided. Added to the surface bubble experiment for testing.

Closes #1243.

I have

- [X] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [X] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [X] There are no open pull requests for this already
- [X] CLIMA developers with relevant expertise have been assigned to review this submission
- [X] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by akshaysridhar** [comment]
Running this against the `surfacebubble` test with `--diagnostics 0.1smins` results in an NCDataset with length `0` in the time dimension 
```
  time   (0)
    Datatype:    Float64
    Dimensions:  time
    Attributes:
     units                = seconds since 1900-01-01 00:00:00
     long_name            = time

  u_prime   (41 × 41 × 41 × 0)
    Datatype:    Float64
    Dimensions:  x × y × z × time

  v_prime   (41 × 41 × 41 × 0)
    Datatype:    Float64
```

**Comment by kpamnany** [comment]
Tested with `--diagnostics=0.1smins` and it seems to produce output correctly. Please recheck with the branch?

**Comment by akshaysridhar** [comment]
@kpamnany This works now.

**Pull request merged**
