### PR TITLE
update CuArrays to 2.2

### LINKED ISSUE #1044: LazyArrays doesn't work with CuArrays 2.1.0
# Description

LazyArrays doesn't play nice with CuArrays 2.1.0

Reproducible example
```
using CuArrays, LazyArrays
CuArrays.allowscalar(false)
a = CuArray(rand(10,3))
W = CuArray(rand(1,3))
reduce(+, @~ W .* a; init=0.0)
```

See Slurm failures on #1004.

We can either fix the issue or find another way to write kernels similar to the above.

cc: @lcw @vchuravy @leios 

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

### PR DESCRIPTION
**Pull request by simonbyrne**
# Description

Fixes #1044, supercedes  #1073 and  #1099.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by simonbyrne** [comment]
Once this is merged, we should look into getting rid of Manifests.

**Comment by simonbyrne** [comment]
Windows!

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by jkozdon** [comment]
Should the title of the PR be updated?

**Comment by simonbyrne** [comment]
Looks like the heat eqn result values changed.

**Comment by simonbyrne** [comment]
the CUDA artifact downloader is generating 16MB log files which breaks our Slurm CI...

**Comment by simonbyrne** [comment]
bors try

**Pull request merged**
