### PR TITLE
Move ocean domains & fields to utilities

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This PR moves/renames the ocean
 - Domains to `Utilities/CartesianDomains` and 
 - Fields to `Utilities/CartesianFields`

In hopes that we can share more of this functionality across more physics components.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Review by glwagner — APPROVED** [review]

**Review by kpamnany — COMMENTED** [review]
I think `Common/` is a better place for these.

**Comment by charleskawczynski** [comment]
bors try-

**Pull request merged**
