### PR TITLE
Move held suarez sources to new tend spec

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

Move sources in Held-Suarez to new tendency specification.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Since `experiments\AtmosGCM\GCMDriver\GCMDriver.jl` does not seem to be used anywhere in the codebase, it would be helpful if someone can run the touched experiments and make sure that things are still running smoothly. cc @LenkaNovak, @bischtob

**Review by LenkaNovak — CHANGES_REQUESTED** [review]
in `heldsuarez_problem.jl` we need to change `boundarycondition` to `boundaryconditions` but otherwise the GCMDriver runs fine :)

**Comment by charleskawczynski** [comment]
> in `heldsuarez_problem.jl` we need to change `boundarycondition` to `boundaryconditions` but otherwise the GCMDriver runs fine :)

Ah, looks like that's actually broken in master. I'm fine with incorporating the fix here. Do the results look okay with these changes?

**Comment by charleskawczynski** [comment]
Bump. I think these are the last of the sources! Would be nice to remove `atmos_source!` in a subsequent PR.

**Review by trontrytel — COMMENTED** [review]
LGTM! I have two questions:
- do we have to define `HeldSuarezForcing()` and `HeldSuarezForcingTutorial()` separately?
- is this part of qa or a longer CI test?

**Comment by charleskawczynski** [comment]
> * do we have to define `HeldSuarezForcing()` and `HeldSuarezForcingTutorial()` separately?

I asked about merging `HeldSuarez` and `HeldSuarezTutorial` a while back, and the consensus was to keep them separate.

> * is this part of qa or a longer CI test?

We just run held suarez, as far as I know. We should really add a QA run for HS.

**Review by trontrytel — APPROVED** [review]
LGTM. I dont know if you want to wait on people that actually run this case. Would be great to add it to qa at some point.

**Review by LenkaNovak — APPROVED** [review]

**Pull request merged**
