### PR TITLE
Add reference val check to test_ocean_gyre.jl

### PR DESCRIPTION
**Pull request by christophernhill**
# Description

This PR adds reference value checking to test_ocean_gyre.jl. Previously this test returned true as long as the code ran. Not it will only return true if statistics for key variables are within tolerance of a set of reference values. 

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [x] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by christophernhill** [comment]
bors try

**Comment by blallen** [comment]
Hey Chris, could you set this up with `experiments/OceanBoxGCM/ocean_gyre.jl` instead? That test runs on slurm, so we can have the integration times go for longer to get more useful state numbers.

I think we should change `test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl` to do a few time steps for a few elements just to make sure that the interface is working properly. Basically split the tests so that what runs on Azure is mostly unit tests/interface tests and that all the real physics tests take place on slurm. Does this make sense to you?

**Comment by christophernhill** [comment]
OK

**Comment by christophernhill** [comment]
bors try

**Comment by christophernhill** [comment]
bors try

**Comment by christophernhill** [comment]
bors try

**Comment by christophernhill** [comment]
bors try

**Comment by christophernhill** [comment]
bors try

**Comment by christophernhill** [comment]
bors try

**Comment by christophernhill** [comment]
bors try

**Pull request merged**
