### PR TITLE
Small bugfix: CUDAevice -> CUDADevice

### PR DESCRIPTION
**Pull request by charleskawczynski**
# Description

Small bugfix: `CUDAevice()` -> `CUDADevice()`

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by jkozdon** [comment]
Is this not being tested / run of the GPU? I don’t understand how this wasn’t hit before?

**Comment by jakebolewski** [comment]
I don't think any of the unit tests are currently tested on the cluster (CPU or GPU).  Should we add that back and is the assumption that all unit tests will pass with the GPU backend?

**Comment by kpamnany** [comment]
> I don't think any of the unit tests are currently tested on the cluster (CPU or GPU). Should we add that back and is the assumption that all unit tests will pass with the GPU backend?

I think so. SlurmCI used to run the unit tests on the GPU (but not on the GPU -- we'd disabled that as being redundant). See [here](https://github.com/CliMA/slurmci/blob/master/scripts/test-gpu-tests.sh).

**Comment by jakebolewski** [comment]
GPU unittests added in #1450

**Comment by charleskawczynski** [comment]
> Is this not being tested / run of the GPU? I don’t understand how this wasn’t hit before?

To add on what's been said, I found this when running `test/runtests.jl` with GPU resources available and, fortunately, I think this was the only failure I found.

**Comment by jkozdon** [comment]
> To add on what's been said, I found this when running test/runtests.jl with GPU resources available and, fortunately, I think this was the only failure I found.

Thanks for checking on this!

**Comment by jakebolewski** [comment]
@charleskawczynski maybe add this as an additional commit to #1450 if that is the case?

**Comment by kpamnany** [comment]
Hmm. Not sure why (`runtests_gpu.jl`](https://github.com/CliMA/ClimateMachine.jl/blob/master/test/runtests_gpu.jl) was running so little then... is this file even being used by anyone else?

**Comment by charleskawczynski** [comment]
> Hmm. Not sure why [`runtests_gpu.jl`](https://github.com/CliMA/ClimateMachine.jl/blob/master/test/runtests_gpu.jl) was running so little then... is this file even being used by anyone else?

Good question, I haven't tried testing that.

Closing this now, since this commit was added to #1450.

**Pull request closed without merging**
