### PR TITLE
Fix and document get_flux_coefficients

### PR DESCRIPTION
**Pull request by ilopezgp**
### Description

This PR resolves issue #2068, by adding documentation of the exchange coefficient formulation, and making the formulation consistent with the SurfaceFluxes module. In particular,

- The new formulation is consistently applicable to both DG and FV discretization.
- The new formulation is general enough to capture any similarity-based vertical profile.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by ilopezgp** [comment]
bors try

**Comment by szy21** [comment]
Thanks Ignacio! It looks good to me. I assume it would be hard to add a unit test?

**Comment by ilopezgp** [comment]
> Thanks Ignacio! It looks good to me. I assume it would be hard to add a unit test?

I am not sure how we would a unit test for now... but the code is being exercised in runtests.jl. an integration test would be easier (against pycles results for example).

**Review by szy21 — APPROVED** [review]

**Pull request merged**
