### PR TITLE
Fix batched GMRES so that it works with non-uniform polynomial orders.

### PR DESCRIPTION
**Pull request by dennisYatunin**
### Small patch for batched GMRES

Whereas code previously used `Nq[1]^(dim - 1)` and `Nq[1]`, now it uses `Nq[1] * Nq[2]` and `Nq[3]`.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by thomasgibson — APPROVED** [review]
LGTM - Thanks!

**Comment by thomasgibson** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Pull request merged**
