### PR TITLE
Add some Vars wrappers

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This PR revives some old work with adding `Vars` wrappers to `BalanceLaws`, so that the DG kernels don't have to wrap arrays with every call. The previous branch I was working on got a bit out of control, so I'm leaning towards doing this more incrementally.

This PR only adds vars wrappers for:
 - `source`
 - `flux_first_order!`
 - `flux_second_order!`

When trying to rely on dispatch between `AbstractArray` and `Vars` methods, I hit method ambiguities (due to, e.g., `source!(::AtmosAcousticLinearModel, _...) = nothing`), so my thought was that appending `_arr` to the array-based methods would be the simplest solution. I'm definitely open to other ideas.

Pros/cons:
 - [con] Performance? (based on observations in #500)
 - [pro] Thins the layer in which `Vars` is used, which makes VariableTemplates closer to being replaceable
 - [pro] Improves readability of DG kernels

I also flattened out a few doc strings to make them a bit more readable.

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by jkozdon — COMMENTED** [review]
This is roughly what I was proposing.

Why do we need the suffix `_arr!`?

I started this for the [numerical fluxes too](https://github.com/CliMA/ClimateMachine.jl/blob/fe19efd685881ead178842fb58363d818582bc7f/src/Numerics/DGMethods/NumericalFluxes.jl#L703-L913) when I did the FVM kernels. But I didn't fully fix the DG kernels; instance [here](https://github.com/CliMA/ClimateMachine.jl/blob/fe19efd685881ead178842fb58363d818582bc7f/src/Numerics/DGMethods/DGModel_kernels.jl#L785-L837) and elsewhere

**Comment by jkozdon** [comment]
I'd be super happy is 'Vars' and 'Grad' were totally gone from the `DGModel_kernels.jl` and `DGFVModel_kernels.jl` files. I think it will make them more formatter friendly and easier to read in general (we shouldn't need to know about vars at this level).

**Comment by jkozdon** [comment]
Also, instead of putting them in a separate file, they could just go in the [`interface.jl`](https://github.com/CliMA/ClimateMachine.jl/blob/fe19efd685881ead178842fb58363d818582bc7f/src/BalanceLaws/interface.jl) file.

**Comment by charleskawczynski** [comment]
> This is roughly what I was proposing.

👍🏻

> Why do we need the suffix _arr!?

At first I didn't have the `_arr` suffix, but then it lead to method ambiguities. We could fix the method ambiguities by changing, for example:
```julia
source!(::AtmosAcousticLinearModel, _...) = nothing
```
to
```julia
source!(
    ::AtmosAcousticLinearModel,
    source::Vars,
    state::Vars,
    diffusive::Vars,
    aux::Vars,
    t::Real,
    direction,
) = nothing
```
but I thought there might be a lot of these (across `source!`, `flux_first_order!`, `flux_second_order!`, `boundary_state!` etc.). So, I figured the suffix might be simpler. I'm open to trying it though. Maybe we'd be able to get away with, e.g., `source!(::AtmosAcousticLinearModel, ::Vars, _...) = nothing`. I'm not sure what the best solution is.

> I started this for the numerical fluxes too when I did the FVM kernels. But I didn't fully fix the DG kernels; instance here and elsewhere

I started working on the numerical fluxes, but things started ballooning, so I decided it might be easier to do this incrementally.

**Comment by jkozdon** [comment]
> > Why do we need the suffix _arr!?
> 
> At first I didn't have the `_arr` suffix, but then it lead to method ambiguities. We could fix the method ambiguities by changing, for example:
> 
> ```julia
> source!(::AtmosAcousticLinearModel, _...) = nothing
> ```
> 
> to
> 
> ```julia
> source!(
>     ::AtmosAcousticLinearModel,
>     source::Vars,
>     state::Vars,
>     diffusive::Vars,
>     aux::Vars,
>     t::Real,
>     direction,
> ) = nothing
> ```
> 
> but I thought there might be a lot of these (across `source!`, `flux_first_order!`, `flux_second_order!`, `boundary_state!` etc.). So, I figured the suffix might be simpler. I'm open to trying it though. Maybe we'd be able to get away with, e.g., `source!(::AtmosAcousticLinearModel, ::Vars, _...) = nothing`. I'm not sure what the best solution is.

This makes sense. `_arr` is fine. I cannot think of anything worse, so stick with it.

Should we be consistent and do the same for the numerical flux wrappers?

 
> > I started this for the numerical fluxes too when I did the FVM kernels. But I didn't fully fix the DG kernels; instance here and elsewhere
> 
> I started working on the numerical fluxes, but things started ballooning, so I decided it might be easier to do this incrementally.

This totally make sense!

**Review by jkozdon — APPROVED** [review]
This is a great start. Thanks!

**Pull request merged**
