### PR TITLE
Make `-` in filenames `_`

### PR DESCRIPTION
**Pull request by jkozdon**
Total bikeshed!

But I noticed that a small number of files used `-` instead of `_` to separate words.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Review by kpamnany — APPROVED** [review]
I like it!

**Comment by jkozdon** [comment]
bors try

**Comment by szy21** [comment]
I like it too! How about those command line arguments? @kpamnany

**Comment by kpamnany** [comment]
> I like it too! How about those command line arguments? @kpamnany

Are you suggesting we use underscores instead of hyphens on the command line? We _could_, but POSIX has a [recommended form](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html), and GNU has a "long options" form, which is what we're using.

**Comment by szy21** [comment]
> Are you suggesting we use underscores instead of hyphens on the command line? We _could_, but POSIX has a [recommended form](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html), and GNU has a "long options" form, which is what we're using.

Oh, I mean, for example, change `--with-moisture` to `--with_moisture`. But either way would be good.

**Comment by kpamnany** [comment]
Try `julia --help`, for example. That's just the protocol...

**Comment by szy21** [comment]
> Try `julia --help`, for example. That's just the protocol...

Ah I didn't know. Thanks!

**Pull request merged**
