### PR TITLE
Upgrade Thermodynamics

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This PR upgrades the version of thermodynamics, which has a bugfix.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
I've updating the bomex mse tables. The tke looks a bit worse in the mse tables, but the profiles don't look terrible IMO, I think we're making faster progress over at TurbulenceConvection.jl on this, so let's just keep this synchronized for now.

**Review by trontrytel — APPROVED** [review]

**Review by yairchn — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Random gpu failures... 😞

**Review by ilopezgp — APPROVED** [review]

**Pull request merged**
