### PR TITLE
update Manifests

### PR DESCRIPTION
**Pull request by simonbyrne**
A bunch of package updates

# Description

A clear and concise description of the code with usage.

I have

- [x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [x] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [x] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by simonbyrne** [comment]
@jakebolewski do you know if it is okay to update CUDA?

**Comment by jakebolewski** [comment]
CUDA.jl the Julia package or CUDA 11?  We don't have a working UCX / CUDA 11 / OpenMPI build on the cluster.

**Comment by simonbyrne** [comment]
CUDA.jl

**Pull request merged**
