### PR TITLE
Update diagnostics groups to handle variable degrees

### PR DESCRIPTION
**Pull request by kpamnany**
### Description

Uses `Grids.basic_grid_info()` and `Topologies.basic_topology_info()` and thereby `grid_info.Nqk`, `grid_info.Nqh`, `grid_info.Nq`, `topl_info.nvertelem` and `topl_info.nhorzrealelem` in all the diagnostics groups that traverse the DG grid.

- [X] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [X] Unit tests are included OR N/A.
- [X] Code is exercised in an integration test OR N/A.
- [X] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
These changes are ready to go, however: in order to test this, we need a couple of working experiments that use different polynomial orders in the horizontal and in the vertical. When those are ready, we would run these changed diagnostics groups in those experiments and have the output eyeballed for correctness.

**Review by skandalaCLIMA — APPROVED** [review]

**Comment by jakebolewski** [comment]
Looks like bomex is timing out.  you can get around this with by adding an additional `slurm_time: "02:00:00"` or something to that test agent.  Although it looks like the runtime has increased substantially over the past couple months

**Pull request merged**
