### PR TITLE
Allow equispaced output in VTK

### PR DESCRIPTION
**Pull request by jkozdon**
Previously only VTK output at the LGL nodes was supported, this allows interpolation to an equidistant grid of points which allows for better visualization.

Co-authored-by:  Thomas Gibson <thomas.gibson@nps.edu>

### CODE REVIEW

**Comment by jkozdon** [comment]
bors try

**Comment by jkozdon** [comment]
Just to be concrete, this is a sample of the output from the acoustic wave with N=4 comparing the new feature (with sampling rate of 10) to the existing plotting of LGL points.

mesh_compare

**Comment by blallen** [comment]
cc: @christophernhill @jm-c this should be useful for visualizing our output

**Pull request merged**
