### PR TITLE
Upgrade some packages (`add GPUCompiler; up GPUCompiler; rm GPUCompiler`)

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

Upgrade package dependencies

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by jakebolewski** [comment]
I don't know if wholesale upgrading is such a good idea as it will make tracking down bugs / regressions much more difficult.

**Comment by charleskawczynski** [comment]
I was going to say that it seems #2146 may be easier to debug.

**Comment by jakebolewski** [comment]
Yeah the 1.6 upgrade I would be in favor of something more systematic.  If we identify particular package needed (ex. CUDA / GPUCompiler) we just try and upgrade the minimal set possible in deliberate steps.

**Comment by kpamnany** [comment]
bors try

**Review by kpamnany — APPROVED** [review]

**Pull request merged**
