### PR TITLE
Bump Open MPI and CUDA versions used on cluster

### PR DESCRIPTION
**Pull request by simonbyrne**
### Description

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Apparently 10.0 is too old for newer CUDA.jl:
https://buildkite.com/clima/climatemachine-ci/builds/651#3909960b-b531-4420-86e7-8839104b3e83/393-791

**Review by jakebolewski — APPROVED** [review]

**Comment by jakebolewski** [comment]
I've updated the default module versions to these as well

**Comment by simonbyrne** [comment]
is this a docs timeout?

**Comment by jakebolewski** [comment]
Yes it looks like it

**Pull request merged**
