### PR TITLE
Make `recover_thermo_state` call `new_thermo_state`

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

See #1648.

This PR should make thermodynamics consistent on the boundaries.

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by trontrytel** [comment]
This is very sad. But you gotta do what you gotta do. 

Could you update the docs as well? https://github.com/CliMA/ClimateMachine.jl/blob/master/docs/src/HowToGuides/Atmos/MoistureModelChoices.md#implementation-notes

**Comment by trontrytel** [comment]
Also, would it be better to get rid of the `recover_thermo_state` function? It is the same as `new_thermo_state`. This will be confusing for people.

**Comment by charleskawczynski** [comment]
> Could you update the docs as well?... Also, would it be better to get rid of the `recover_thermo_state` function? It is the same as `new_thermo_state`. This will be confusing for people.

I'm hesitant to make too many changes. I don't know to what degree this will impact performance.

**Comment by trontrytel** [comment]
> > Could you update the docs as well?... Also, would it be better to get rid of the `recover_thermo_state` function? It is the same as `new_thermo_state`. This will be confusing for people.
> 
> I'm hesitant to make too many changes. I don't know to what degree this will impact performance.

How do you want to test that then? 
Keeping the docs as they are and keeping two functions that do the same thing is dangerous.

**Comment by charleskawczynski** [comment]
Updated.

**Review by trontrytel — APPROVED** [review]
Thanks!

**Pull request merged**
