### PR TITLE
Wrap some runtests in modules

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

This PR wraps some `runtests.jl` in modules. A step towards #1368.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by kpamnany — COMMENTED** [review]
LGTM, but I don't know that I fully understand the issues so will leave this to Jake to approve.

**Review by jakebolewski — APPROVED** [review]

**Pull request merged**
