### PR TITLE
Introduce `AbstractProblem` and `AtmosProblem`

### PR DESCRIPTION
**Pull request by kpamnany**
# Description

To separate the specification of initial and boundary conditions from the specification of the model. This is already done in the Ocean code.

Towards addressing #1356. The BOMEX prototype that uses this capability remains TBD.

I have

- [X] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [X] There are no open pull requests for this already
- [X] CLIMA developers with relevant expertise have been assigned to review this submission
- [X] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [X] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
bors try

**Comment by simonbyrne** [comment]
This seems like a good solution.

**Comment by blallen** [comment]
Right now `AtmosProblem` only has `boundarycondition`, `init_state_prognostic!`, and `init_state_auxiliary!`. One of the benefits of the problem concept is that you can store parameters related to those three functions in the problem itself, so that the model doesn't store parameters that aren't always used. Are you guys considering doing that?

**Comment by kpamnany** [comment]
@blallen: please expand? What sort of parameters?

**Comment by kpamnany** [comment]
@szy21: I've merged the two BOMEX drivers into one (in [this commit](https://github.com/CliMA/ClimateMachine.jl/pull/1415/commits/124a3fcc9051bee4be2e784dc95da7c08f9d8565)). Can you please take a look -- pull this branch -- and make sure I haven't messed it up?

**Comment by szy21** [comment]
> this commit

Oh great! Let me take a look.

**Comment by szy21** [comment]
@kpamnany BOMEX works, thanks! As I mentioned it might be better to have surface_flux = 'prescribed', 'bulk', 'monin-obukhov', etc.. This is not specific to BOMEX, the only reason we add this is right now there are no unit tests or drivers that use the new boundary condition functions, and we add it to BOMEX so the functions don't go stale.

I wonder in general what we should put in command line arguments? We will have many other things that people would like to change in the driver in the future. Previously it is done through a namelist, but I'm not sure what CliMA's plan is.

**Comment by blallen** [comment]
> @blallen: please expand? What sort of parameters?

Here's what we have for the Ocean https://github.com/CliMA/ClimateMachine.jl/blob/124a3fcc9051bee4be2e784dc95da7c08f9d8565/src/Ocean/OceanProblems/SimpleBoxProblem.jl#L249-L255

`Lˣ, Lʸ, H` are the dimensions of the physical domain and are used in `ocean_init_state!`
https://github.com/CliMA/ClimateMachine.jl/blob/124a3fcc9051bee4be2e784dc95da7c08f9d8565/src/Ocean/OceanProblems/SimpleBoxProblem.jl#L286-L296

`τₒ` is used in the velocity boundary condition (this function is called in the BC code)
https://github.com/CliMA/ClimateMachine.jl/blob/124a3fcc9051bee4be2e784dc95da7c08f9d8565/src/Ocean/OceanProblems/SimpleBoxProblem.jl#L318-L319

`λʳ, θᴱ` are used in the temperature boundary condition (this function is called in the BC code)
https://github.com/CliMA/ClimateMachine.jl/blob/124a3fcc9051bee4be2e784dc95da7c08f9d8565/src/Ocean/OceanProblems/SimpleBoxProblem.jl#L336-L343

Maybe it's a better idea to have the parameters for the boundary conditions be attached to the BoundaryCondition structs themselves instead of in the problem. I'm not sure where AtmosModel stores the domain parameters right now.

**Comment by kpamnany** [comment]
> @kpamnany BOMEX works, thanks! As I mentioned it might be better to have surface_flux = 'prescribed', 'bulk', 'monin-obukhov', etc.. This is not specific to BOMEX, the only reason we add this is right now there are no unit tests or drivers that use the new boundary condition functions, and we add it to BOMEX so the functions don't go stale.

Ah, I understand now. Will discuss this with you to properly generalize.

> I wonder in general what we should put in command line arguments? We will have many other things that people would like to change in the driver in the future. Previously it has been done through a namelist, but I'm not sure what CliMA's plan is.

We will add namelist-like functionality, but the exact form is not yet defined. I have a couple of ideas, but again, we can discuss.

**Comment by charleskawczynski** [comment]
> Right now `AtmosProblem` only has `boundarycondition`, `init_state_prognostic!`, and `init_state_auxiliary!`. One of the benefits of the problem concept is that you can store parameters related to those three functions in the problem itself, so that the model doesn't store parameters that aren't always used. Are you guys considering doing that?

Idk that we need to put parameters inside the `Problem`. I think a convenient and flexible alternative, for now, would be to define methods for pieces we need and dispatching on the `Problem`, rather than making them properties of the `Problem`. If we see a pattern that many problems need certain parameters, we can add properties, but I think problems often have quite different configurations.

**Comment by kpamnany** [comment]
@LenkaNovak: I've merged moist baroclinic wave into baroclinic wave. Can you please take a look?

**Comment by kpamnany** [comment]
I'm going to defer demonstrating use of `AbstractProblem` to separate PRs:
- When the single stack BOMEX version is ready, @charleskawczynski and I will merge that into the current BOMEX.
- @LenkaNovak and I will soon open a PR that will create a generalized GCM driver that can be used by Held Suarez and baroclinic wave (as well as by other experiments she is developing) which will also make use of the problem abstraction.

**Pull request merged**
