### PR TITLE
Reverts #1086

### LINKED ISSUE #1111: Revert #1086
# Description

#1086 accidentally reverted several PRs, so this PR should probably be reverted as it included undoing several important documentation changes (several of which were for our v0.1 milestone).

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

### PR DESCRIPTION
**Pull request by vchuravy**
Merge/rebase mistake caused several commits to be reverted in #1086
this only applies the intended changes from #1086 and thus fixes #1111

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Looks like this adds the right pieces back in. I'll review the docs once it's finished building. Also, is `Formatting` needed in the Manifest? It looks like Chris uses it [here](https://github.com/CliMA/ClimateMachine.jl/pull/1086/files#diff-587a13d4cef00526b80b09bbe6454c6fR20) in #1086.

**Comment by vchuravy** [comment]
No I just missed a change.

**Comment by vchuravy** [comment]
Ok doing a hard revert for now, and then we can reland #1086 afterwards.

**Pull request merged**
