### PR TITLE
Move `ConfigTypes` and `Checkpoint` into `Driver/`

### PR DESCRIPTION
**Pull request by kpamnany**
# Description

Since both really belong there. Should have no effect on anything as they are still `ClimateMachine` sub-modules.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [X] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [X] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [X] There are no open pull requests for this already
- [X] CLIMA developers with relevant expertise have been assigned to review this submission
- [X] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
LGTM

**Review by blallen — APPROVED** [review]
I like it, is there any reason for not making ConfigTypes and Checkpoint submodules of the Driver module besides avoiding breaking changes?

**Comment by kpamnany** [comment]
> I like it, is there any reason for not making ConfigTypes and Checkpoint submodules of the Driver module besides avoiding breaking changes?

`Driver` isn't a module -- it's the `ClimateMachine` top-level.

**Comment by blallen** [comment]
> > I like it, is there any reason for not making ConfigTypes and Checkpoint submodules of the Driver module besides avoiding breaking changes?
> 
> `Driver` isn't a module -- it's the `ClimateMachine` top-level.

Ah okay, makes sense then!

**Pull request merged**
