### PR TITLE
Move atmos.moisture to atmos.physics

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
Supersedes #2100. I don't think we'll need to change the drivers because the added layer will give us the flexibility to construct necessary BC data structures in the `AtmosModel` constructor.

**Comment by charleskawczynski** [comment]
bors try

**Review by kpamnany — APPROVED** [review]

**Pull request merged**
