### PR TITLE
Extract remaining citations

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

Extracts remaining references/citations to `docs/bibliography.bib`.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by trontrytel** [comment]
This is great. However I think there is something wrong in how the References page is rendered. The entries are listed based on the labels given to them in the code and not by the first author name or year. 

Also, before this change, clicking on the links in my docs would lead to the relevant paper available on the journal page. Now it just leads to the References page. And the links in the Reference page are placed weirdly and in general lead back to the References page and not the paper.

**Comment by charleskawczynski** [comment]
> However I think there is something wrong in how the References page is rendered.

I agree that it doesn't look great right now, but I think we can improve things in `DocumenterCitations.jl` and the reference page will eventually look better as we upgrade.

> The entries are listed based on the labels given to them in the code and not by the first author name or year.

I'm not sure I understand. Can you give an example?

> Also, before this change, clicking on the links in my docs would lead to the relevant paper available on the journal page. Now it just leads to the References page. And the links in the Reference page are placed weirdly and in general lead back to the References page and not the paper.

That's a good point. Ideally, each entry would be placed inside an HTML tag with an `active` attribute so that when someone clicks on one of the references, it could activate the HTML attribute so that the entry is highlighted. I think that this is something that can also be improved on the `DocumenterCitations.jl` side.

**Comment by trontrytel** [comment]
> > The entries are listed based on the labels given to them in the code and not by the first author name or year.
> 
> I'm not sure I understand. Can you give an example?
> 
> >

Screenshot 2020-11-02 at 09 25 11

**Comment by trontrytel** [comment]
> > Also, before this change, clicking on the links in my docs would lead to the relevant paper available on the journal page. Now it just leads to the References page. And the links in the Reference page are placed weirdly and in general lead back to the References page and not the paper.
> 
> That's a good point. Ideally, each entry would be placed inside an HTML tag with an `active` attribute so that when someone clicks on one of the references, it could activate the HTML attribute so that the entry is highlighted. I think that this is something that can also be improved on the `DocumenterCitations.jl` side.

I'm not sure I understand. My point is that it's way more useful for the links to point to the actual paper than to a reference list based on which you have to find the paper.

**Comment by charleskawczynski** [comment]
> I'm not sure I understand. My point is that it's way more useful for the links to point to the actual paper than to a reference list based on which you have to find the paper.

Wouldn't it still be useful if we included direct links to the paper in the reference entry? I think that between including direct links and highlighting the clicked entry, navigating citations would be very easy.

**Comment by trontrytel** [comment]
> > I'm not sure I understand. My point is that it's way more useful for the links to point to the actual paper than to a reference list based on which you have to find the paper.
> 
> Wouldn't it still be useful if we included direct links to the paper in the reference entry? Right now they're broken (and there are obviously formatting issues), but that's a `DocumenterCitation` problem. I think that navigating citations would be very easy between including direct links and highlighting the clicked entry.

I agree. If the links in the reference page work I'm fine with it. 

I guess we want the reference page to safeguard against when the link stops working and you still want to be able to find the paper by yourself.

**Comment by charleskawczynski** [comment]
> I guess we want the reference page to safeguard against when the link stops working and you still want to be able to find the paper by yourself.

That's a good point, we should make sure that Documenter still checks the links after `References.md` has been generated.

**Comment by jkozdon** [comment]
We should make sure we use doi numbers and links when possible, this will safeguard against links breaking.

**Comment by charleskawczynski** [comment]
> I don't see any dois listed in the references page, can we add that?

Yes, most of the refs I grabbed were from Google Scholar, but not all of them had doi links, so we'll need a second pass to add them where possible.

**Comment by simonbyrne** [comment]
The links are based on the doi when it is available. We should add them to the bibtex entries.

**Comment by jkozdon** [comment]
> The links are based on the doi when it is available. We should add them to the bibtex entries.

I see that now. I just didn't mouse over the ones that were.

**Comment by charleskawczynski** [comment]
bump

**Comment by trontrytel** [comment]
> bump

Are the links pointing to the actual papers working now in the docs?

**Comment by trontrytel** [comment]
Also, the references are still not sorted in any order?

**Comment by charleskawczynski** [comment]
> Are the links pointing to the actual papers working now in the docs? Some of them seem to work, but most do not.

Ahh, I can see that not all entries I used included URLs, I'll go and fix the ones that we previously had.

> Also, the references are still not sorted in any order?

No, IMO, that's a problem that we can ship off for `DocumenterCitations` to solve-- and we should be able to fix it through an upgrade to a newer version which solves this problem.

**Comment by trontrytel** [comment]
> > Are the links pointing to the actual papers working now in the docs? Some of them seem to work, but most do not.
> 
> Ahh, I can see that not all entries I used included URLs, I'll go and fix the ones that we previously had.
> 
> > Also, the references are still not sorted in any order?
> 
> No, IMO, that's a problem that we can ship off for `DocumenterCitations` to solve-- and we should be able to fix it through an upgrade to a newer version which solves this problem.

Sounds good. IMHO I don't care about formatting of the reference list. But I think that links should end up pointing to papers

**Comment by charleskawczynski** [comment]
Updated.

**Comment by charleskawczynski** [comment]
> Looks like now it's timing out?

I think I just haven't tried rebuilding now that the docs are run on the cluster

**Comment by charleskawczynski** [comment]
Bump

**Review by simonbyrne — APPROVED** [review]

**Comment by simonbyrne** [comment]
Thanks!

**Comment by trontrytel** [comment]
For me the links in the references are still mostly not working. So in my book it's change for worse. But if everyone else disagrees, please merge

**Comment by charleskawczynski** [comment]
> For me the links in the references are still mostly not working. So in my book it's change for worse. But if everyone else disagrees, please merge

Which link(s)?

**Comment by simonbyrne** [comment]
https://clima.github.io/ClimateMachine.jl/previews/PR1687/References/#Smagorinsky1963

**Comment by trontrytel** [comment]
> > For me the links in the references are still mostly not working. So in my book it's change for worse. But if everyone else disagrees, please merge
> 
> Which link(s)?

For example the first two Toro2013 and Rutledge1983 entries have links that for me point back to the reference page

**Comment by charleskawczynski** [comment]
Ok, I think the links that point to the references page can be fixed upstream.

The smagorinsky entry is wrong, I see that I accidentally copied entries of Lilly model and put them into the Smagorinsky model. I’ll fix that tomorrow.

Perhaps we can merge after that and we can try to tackle some of the upstream issues (I’ll make sure to open an upstream issue regarding the links that aren’t working).

**Comment by charleskawczynski** [comment]
Thanks for reviewing!

**Pull request merged**
