### PR TITLE
docs: fix subscripts on math equations in Driver/SolverTypes/

### PR DESCRIPTION
**Pull request by haakon-e**
# Description

Add curly brackets to equation text that should be subscript. See the [relevant docs](https://clima.github.io/ClimateMachine.jl/latest/APIs/Driver/#ClimateMachine.MISSolverType) for current behavior.

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by charleskawczynski** [comment]
LGTM, let's squash and merge. @haakon-e can you squash?

**Comment by haakon-e** [comment]
I squashed the commits @charleskawczynski. I couldn't find if you have a style guide for git messages, let me know if it looks good.

**Comment by charleskawczynski** [comment]
>  I couldn't find if you have a style guide for git messages

Good point. At first glance, I don’t see a style guide specifically for git messages in our current [contribution guide](https://clima.github.io/ClimateMachine.jl/latest/Contributing/). Regardless looks good. Thanks for the contribution!

**Pull request merged**
