### PR TITLE
Interpolation + vardeg tests + bug fix

### PR DESCRIPTION
**Pull request by skandalaCLIMA**
Tests, which use different polynomial orders in horizontal and vertical directions, added.
Bugs, effecting interpolation code when different polynomial orders are
used in horizontal and vertical directions, are fixed.

### Description

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by skandalaCLIMA** [comment]
bors try

**Comment by skandalaCLIMA** [comment]
bors try

**Comment by skandalaCLIMA** [comment]
bors try

**Review by kpamnany — APPROVED** [review]

**Comment by kpamnany** [comment]
@skandalaCLIMA: the CI failure on the last r+ is an interpolation test error, a error above the tolerance. Is this explainable?

**Comment by skandalaCLIMA** [comment]
> @skandalaCLIMA: the CI failure on the last r+ is an interpolation test error, a error above the tolerance. Is this explainable?

It's a weird error. The GPU test is within the tolerance on Caltech GPU cluster. It also runs fine with bors try. Not sure why this broke with bors r+.

**Pull request merged**
