### PR TITLE
Fix code coverage cron job after CLIMA -> ClimateMachine rename

### LINKED ISSUE #1093: Code Coverage Broken after Pkg rename
Code coverage is broken after CLIMA -> ClimateMachine.jl rename.
Github action workflow needs to be updated to reflect the name change.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

### PR DESCRIPTION
**Pull request by jakebolewski**
Also align code coverage OS with OS variant tested under current Linux CI

Closes #1093 

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [ ] There are no open pull requests for this already
- [ ] CLIMA developers with relevant expertise have been assigned to review this submission
- [ ] The code conforms to the [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by charleskawczynski** [comment]
@jakebolewski might as well adjust the README URL, too!

**Comment by jakebolewski** [comment]
bors merge

**Comment by charleskawczynski** [comment]
> 🔒 Permission denied
> 
> Existing reviewers: [click here to make jakebolewski a reviewer](https://app.bors.tech/repositories/11521/add-reviewer/jakebolewski)

I clicked into this, and it said @jakebolewski was already a reviewer, but it seemed that the page immediately needed to reload. I _think_ that should be fixed, we'll see next time.

**Comment by kpamnany** [comment]
> it said @jakebolewski was already a reviewer

I fixed it earlier.

**Pull request merged**
