### PR TITLE
add CFL direction in bomex_les.jl

### PR DESCRIPTION
**Pull request by szy21**
# Description

add CFL_direction = HorizontalDirection() and change CFLmax to 0.35 in bomex_les.jl

I have

- [ ] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ ] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ ] Updated the documentation to reflect changes from this PR.

# For review by CLIMA developers

- [x] There are no open pull requests for this already
- [x] CLIMA developers with relevant expertise have been assigned to review this submission
- [x] The code conforms to the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and has consistent naming conventions. `julia .dev/format.jl` has been run in a separate commit.
- [ ] This code does what it is technically intended to do (all numerics make sense physically and/or computationally)

### CODE REVIEW

**Comment by akshaysridhar** [comment]
Could you please run this against the 6 hour `timeend` to verify the statistics are reasonable ? If so the changes are minimal and I can merge this

**Review by charleskawczynski — APPROVED** [review]
Looks fine by me. Is this to make the simulation more stable?

**Comment by akshaysridhar** [comment]
> Looks fine by me. Is this to make the simulation more stable?



> Looks fine by me. Is this to make the simulation more stable?

Clarifies usage of the keyword CFL_direction - it isn't set up in the Driver.jl defaults right now for the IMEX method; but we can set it at the experiment level.

**Comment by szy21** [comment]
> Could you please run this against the 6 hour `timeend` to verify the statistics are reasonable ? If so, the changes are minimal and I can merge this

I have run a 6 hour simulation and the results look reasonable.

**Review by akshaysridhar — APPROVED** [review]

**Pull request merged**
