### PR TITLE
Support AbstractArray in getpropertyorindex in VariableTemplates

### PR DESCRIPTION
**Pull request by charleskawczynski**
### Description

Trying to break #1931 into bits to figure out what is breaking the system image build.

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
.....well that’s surprising. @kpamnany any ideas?

**Comment by kpamnany** [comment]
I was looking at this. Tried out a few things in a REPL. There's a Julia bug here I think, but I don't know how to get to the bottom of it. @vchuravy: any ideas?

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
bors try

**Comment by kpamnany** [comment]
bors try

**Comment by charleskawczynski** [comment]
We don't really need this anymore

**Pull request closed without merging**
