### PR TITLE
Test scalar hyperdiffusion with boundary conditions

### PR DESCRIPTION
**Pull request by mwarusz**
As a first step towards supporting boundary conditions for hyperdiffusion this PR modifies the advection-(hyper)diffusion model to support boundary conditions for hyperdiffusion and adds a test for various types of boundary conditions that can be prescribed.
 

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Comment by mwarusz** [comment]
bors try

**Review by jkozdon — APPROVED** [review]

**Pull request merged**
