### PR TITLE
MIS method docstrings

### PR DESCRIPTION
**Pull request by valeriabarra**
### Description
This PR adds some MIS Time Stepping method docstrings that were missing, so that they can show up in our API docs. 

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Comment by charleskawczynski** [comment]
Thanks for helping out with the bibliography!

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
I reduced the number of commits in this PR. This is ready for review. Thanks

**Review by bischtob — APPROVED** [review]
LGTM!

**Pull request merged**
