### PR TITLE
Read EDMF parameters from CLIMAParameters

### PR DESCRIPTION
**Pull request by ilopezgp**
### Description

Read EDMF parameters from CLIMAParameters. Apart from this, I have cleaned up one duplicated parameter (H_up_min in EntrainmentDetrainment).

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by ilopezgp** [comment]
@charleskawczynski should I update the Project.toml?

**Comment by ilopezgp** [comment]
bors try

**Comment by ilopezgp** [comment]
bors try

**Comment by ilopezgp** [comment]
bors try

**Review by charleskawczynski — APPROVED** [review]
LGTM

**Pull request merged**
