### PR TITLE
Conformal cubed-sphere

### PR DESCRIPTION
**Pull request by valeriabarra**
Warp tests pass. Now need to work on inverse unwarp function

### Description

This PR adds a conformal cubed-sphere (the same one used in `Oceananigans.jl` to also facilitate initial coupling in the `CouplerMachine`). So far the `warp` function has been added and fully tested. This PR would add a dependency on `CubedSphere.jl` and `Rotations.jl`, for the function needed to generate the conformal cubed-sphere grid (points location).

At the moment, we don't have a corresponding `unwarp` function.
Any help in formulating the inverse function (i.e., `unwarp`) would be really appreciated. Thanks. 

cc: @jkozdon 

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
bors try-

**Comment by valeriabarra** [comment]
CI failure unrelated to this PR. I won't trigger `bors` until new functionality is added that needs to be tested

**Review by jkozdon — COMMENTED** [review]
Not sure I have much input, but this seem reasonable to me.

> At the moment, we don't have a corresponding unwarp function.
Any help in formulating the inverse function (i.e., unwarp) would be really appreciated. Thanks.

Can you just use Newton's method with something like automatic differentiation? (Not sure how performant it really needs to be?)

**Comment by valeriabarra** [comment]
Resuscitating this branch. Rebased onto current master

**Comment by valeriabarra** [comment]
bors try

**Review by simonbyrne — APPROVED** [review]

**Comment by simonbyrne** [comment]
I think it's okay to not worry about the unwarp for now.

**Pull request merged**
