### PR TITLE
force documenter previews on bors trying branches

### PR DESCRIPTION
**Pull request by jakebolewski**
### Description

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try-

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
@trontrytel this is a workaround that enables `bors try` to push previews of the tutorials to the same PR `gh-pages` URL.

**Review by charleskawczynski — APPROVED** [review]
LGTM, this will allow us to previews on b-o-r-s try?

**Comment by jakebolewski** [comment]
Yep, this just kind of mocks a bors try run to be a "buildkite pr"

bors r+

**Pull request merged**
